/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SalesRouteImport } from "./routes/sales";
import { Route as ProductsRouteImport } from "./routes/products";
import { Route as PosRouteImport } from "./routes/pos";
import { Route as InventoryRouteImport } from "./routes/inventory";
import { Route as CatalogRouteImport } from "./routes/catalog";
import { Route as IndexRouteImport } from "./routes/index";

const SalesRoute = SalesRouteImport.update({
  id: "/sales",
  path: "/sales",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsRoute = ProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => rootRouteImport,
} as any);
const PosRoute = PosRouteImport.update({
  id: "/pos",
  path: "/pos",
  getParentRoute: () => rootRouteImport,
} as any);
const InventoryRoute = InventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => rootRouteImport,
} as any);
const CatalogRoute = CatalogRouteImport.update({
  id: "/catalog",
  path: "/catalog",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/catalog": typeof CatalogRoute;
  "/inventory": typeof InventoryRoute;
  "/pos": typeof PosRoute;
  "/products": typeof ProductsRoute;
  "/sales": typeof SalesRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/catalog": typeof CatalogRoute;
  "/inventory": typeof InventoryRoute;
  "/pos": typeof PosRoute;
  "/products": typeof ProductsRoute;
  "/sales": typeof SalesRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/catalog": typeof CatalogRoute;
  "/inventory": typeof InventoryRoute;
  "/pos": typeof PosRoute;
  "/products": typeof ProductsRoute;
  "/sales": typeof SalesRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/catalog" | "/inventory" | "/pos" | "/products" | "/sales";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/catalog" | "/inventory" | "/pos" | "/products" | "/sales";
  id: "__root__" | "/" | "/catalog" | "/inventory" | "/pos" | "/products" | "/sales";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CatalogRoute: typeof CatalogRoute;
  InventoryRoute: typeof InventoryRoute;
  PosRoute: typeof PosRoute;
  ProductsRoute: typeof ProductsRoute;
  SalesRoute: typeof SalesRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sales": {
      id: "/sales";
      path: "/sales";
      fullPath: "/sales";
      preLoaderRoute: typeof SalesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products": {
      id: "/products";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof ProductsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pos": {
      id: "/pos";
      path: "/pos";
      fullPath: "/pos";
      preLoaderRoute: typeof PosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/inventory": {
      id: "/inventory";
      path: "/inventory";
      fullPath: "/inventory";
      preLoaderRoute: typeof InventoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/catalog": {
      id: "/catalog";
      path: "/catalog";
      fullPath: "/catalog";
      preLoaderRoute: typeof CatalogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  InventoryRoute: InventoryRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  SalesRoute: SalesRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
