package audit

const (
	EventAuthRefreshed     = "auth.refreshed"
	EventAuthRefreshReused = "auth.refresh.reused"
	EventAuthLoggedOut     = "auth.logged_out"
	EventAuthLoggedOutAll  = "auth.logged_out_all"
	EventSessionRevoked    = "session.revoked"

	EventAuthRegistered        = "auth.registered"
	EventAuthLoginSucceeded    = "auth.login.succeeded"
	EventAuthLoginFailed       = "auth.login.failed"
	EventAuthContextChanged    = "auth.context.changed"
	EventAuthPasswordChanged   = "auth.password.changed"
	EventAuthPasswordResetReq  = "auth.password.reset_requested"
	EventAuthPasswordResetComp = "auth.password.reset_completed"
	EventAuthEmailVerified     = "auth.email.verified"
	EventOrganizationCreated   = "organization.created"
	EventOrganizationUpdated   = "organization.updated"
	EventOrganizationArchived  = "organization.archived"
	EventStoreCreated          = "store.created"
	EventStoreUpdated          = "store.updated"
	EventStoreStatusChanged    = "store.status_changed"
	EventMembershipInvited     = "membership.invited"
	EventMembershipJoined      = "membership.joined"
	EventMembershipSuspended   = "membership.suspended"
	EventMembershipReactivated = "membership.reactivated"
	EventMembershipRemoved     = "membership.removed"
	EventRoleCreated           = "role.created"
	EventRoleUpdated           = "role.updated"
	EventRoleStatusChanged     = "role.status_changed"
	EventRoleBindingAdded      = "role.binding_added"
	EventRoleBindingRemoved    = "role.binding_removed"
)
