export const SCOPE_VALUES = [
  "organization.read",
  "organization.update",
  "organization.archive",
  "organization.owners.manage",
  "stores.read",
  "stores.create",
  "stores.update",
  "stores.status.update",
  "members.read",
  "members.invite",
  "members.status.update",
  "members.remove",
  "invitations.read",
  "invitations.manage",
  "scopes.read",
  "roles.read",
  "roles.create",
  "roles.update",
  "roles.status.update",
  "roles.assign",
  "audit.read",
  "products.read",
  "products.create",
  "products.update",
  "products.status.update",
  "categories.read",
  "categories.create",
  "categories.update",
  "categories.status.update",
  "payment_methods.manage",
  "catalog.read",
  "inventory.read",
  "inventory.entries.create",
  "inventory.adjustments.create",
  "inventory.movements.read",
  "sales.read",
  "sales.create",
  "sales.items.manage",
  "sales.cancel",
  "sales.checkout",
  "payment_methods.read",
  "payments.read",
  "fiscal.read",
  "receipts.read",
] as const;

export type Scope = (typeof SCOPE_VALUES)[number];
