// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT COUNT(*)
FROM security_audit_events
WHERE organization_id = $1
  AND (
      CAST($2 AS UUID) IS NULL
      OR store_id = CAST($2 AS UUID)
  )
  AND (
      CAST($3 AS UUID) IS NULL
      OR actor_user_id = CAST($3 AS UUID)
  )
  AND (
      CAST($4 AS UUID) IS NULL
      OR actor_membership_id = CAST($4 AS UUID)
  )
  AND (
      CAST($5 AS TEXT) IS NULL
      OR event_type = CAST($5 AS TEXT)
  )
  AND (
      CAST($6 AS audit_outcome) IS NULL
      OR outcome = CAST($6 AS audit_outcome)
  )
  AND (
      CAST($7 AS TEXT) IS NULL
      OR entity_type = CAST($7 AS TEXT)
  )
  AND (
      CAST($8 AS UUID) IS NULL
      OR entity_id = CAST($8 AS UUID)
  )
  AND (
      CAST($9 AS TIMESTAMPTZ) IS NULL
      OR occurred_at >= CAST($9 AS TIMESTAMPTZ)
  )
  AND (
      CAST($10 AS TIMESTAMPTZ) IS NULL
      OR occurred_at < CAST($10 AS TIMESTAMPTZ)
  )
`

type CountAuditEventsParams struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ActorUserID       pgtype.UUID
	ActorMembershipID pgtype.UUID
	EventType         pgtype.Text
	Outcome           NullAuditOutcome
	EntityType        pgtype.Text
	EntityID          pgtype.UUID
	OccurredFrom      pgtype.Timestamptz
	OccurredTo        pgtype.Timestamptz
}

func (q *Queries) CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents,
		arg.OrganizationID,
		arg.StoreID,
		arg.ActorUserID,
		arg.ActorMembershipID,
		arg.EventType,
		arg.Outcome,
		arg.EntityType,
		arg.EntityID,
		arg.OccurredFrom,
		arg.OccurredTo,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO security_audit_events (
    organization_id,
    store_id,
    actor_user_id,
    actor_membership_id,
    session_id,
    event_type,
    entity_type,
    entity_id,
    request_id,
    ip_address,
    user_agent,
    outcome,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING
    id,
    organization_id,
    store_id,
    actor_user_id,
    actor_membership_id,
    session_id,
    event_type,
    entity_type,
    entity_id,
    request_id,
    ip_address,
    user_agent,
    outcome,
    metadata,
    occurred_at
`

type CreateAuditEventParams struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ActorUserID       pgtype.UUID
	ActorMembershipID pgtype.UUID
	SessionID         pgtype.UUID
	EventType         string
	EntityType        pgtype.Text
	EntityID          pgtype.UUID
	RequestID         pgtype.Text
	IpAddress         *netip.Addr
	UserAgent         pgtype.Text
	Outcome           AuditOutcome
	Metadata          []byte
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (SecurityAuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.OrganizationID,
		arg.StoreID,
		arg.ActorUserID,
		arg.ActorMembershipID,
		arg.SessionID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.RequestID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Outcome,
		arg.Metadata,
	)
	var i SecurityAuditEvent
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.ActorUserID,
		&i.ActorMembershipID,
		&i.SessionID,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.RequestID,
		&i.IpAddress,
		&i.UserAgent,
		&i.Outcome,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT
    id,
    organization_id,
    store_id,
    actor_user_id,
    actor_membership_id,
    session_id,
    event_type,
    entity_type,
    entity_id,
    request_id,
    ip_address,
    user_agent,
    outcome,
    metadata,
    occurred_at
FROM security_audit_events
WHERE organization_id = $1
  AND (
      CAST($2 AS UUID) IS NULL
      OR store_id = CAST($2 AS UUID)
  )
  AND (
      CAST($3 AS UUID) IS NULL
      OR actor_user_id = CAST($3 AS UUID)
  )
  AND (
      CAST($4 AS UUID) IS NULL
      OR actor_membership_id = CAST($4 AS UUID)
  )
  AND (
      CAST($5 AS TEXT) IS NULL
      OR event_type = CAST($5 AS TEXT)
  )
  AND (
      CAST($6 AS audit_outcome) IS NULL
      OR outcome = CAST($6 AS audit_outcome)
  )
  AND (
      CAST($7 AS TEXT) IS NULL
      OR entity_type = CAST($7 AS TEXT)
  )
  AND (
      CAST($8 AS UUID) IS NULL
      OR entity_id = CAST($8 AS UUID)
  )
  AND (
      CAST($9 AS TIMESTAMPTZ) IS NULL
      OR occurred_at >= CAST($9 AS TIMESTAMPTZ)
  )
  AND (
      CAST($10 AS TIMESTAMPTZ) IS NULL
      OR occurred_at < CAST($10 AS TIMESTAMPTZ)
  )
ORDER BY occurred_at DESC, id DESC
LIMIT $12
OFFSET $11
`

type ListAuditEventsParams struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ActorUserID       pgtype.UUID
	ActorMembershipID pgtype.UUID
	EventType         pgtype.Text
	Outcome           NullAuditOutcome
	EntityType        pgtype.Text
	EntityID          pgtype.UUID
	OccurredFrom      pgtype.Timestamptz
	OccurredTo        pgtype.Timestamptz
	PageOffset        int32
	PageSize          int32
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]SecurityAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.OrganizationID,
		arg.StoreID,
		arg.ActorUserID,
		arg.ActorMembershipID,
		arg.EventType,
		arg.Outcome,
		arg.EntityType,
		arg.EntityID,
		arg.OccurredFrom,
		arg.OccurredTo,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityAuditEvent{}
	for rows.Next() {
		var i SecurityAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.ActorUserID,
			&i.ActorMembershipID,
			&i.SessionID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.RequestID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Outcome,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
