// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeActionToken = `-- name: ConsumeActionToken :one
UPDATE auth_action_tokens
SET consumed_at = NOW()
WHERE id = $1
  AND user_id = $2
  AND purpose = $3
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING
    id,
    user_id,
    purpose,
    consumed_at
`

type ConsumeActionTokenParams struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	Purpose AuthActionTokenPurpose
}

type ConsumeActionTokenRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Purpose    AuthActionTokenPurpose
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) ConsumeActionToken(ctx context.Context, arg ConsumeActionTokenParams) (ConsumeActionTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeActionToken, arg.ID, arg.UserID, arg.Purpose)
	var i ConsumeActionTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.ConsumedAt,
	)
	return i, err
}

const createActionToken = `-- name: CreateActionToken :one
INSERT INTO auth_action_tokens (
    id,
    user_id,
    purpose,
    secret_hash,
    expires_at,
    requested_ip
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    user_id,
    purpose,
    secret_hash,
    expires_at,
    consumed_at,
    requested_ip,
    created_at
`

type CreateActionTokenParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Purpose     AuthActionTokenPurpose
	SecretHash  []byte
	ExpiresAt   pgtype.Timestamptz
	RequestedIp *netip.Addr
}

func (q *Queries) CreateActionToken(ctx context.Context, arg CreateActionTokenParams) (AuthActionToken, error) {
	row := q.db.QueryRow(ctx, createActionToken,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.SecretHash,
		arg.ExpiresAt,
		arg.RequestedIp,
	)
	var i AuthActionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RequestedIp,
		&i.CreatedAt,
	)
	return i, err
}

const getActionTokenForUpdate = `-- name: GetActionTokenForUpdate :one
SELECT
    id,
    user_id,
    purpose,
    secret_hash,
    expires_at,
    consumed_at,
    requested_ip,
    created_at
FROM auth_action_tokens
WHERE id = $1
  AND purpose = $2
FOR UPDATE
`

type GetActionTokenForUpdateParams struct {
	ID      pgtype.UUID
	Purpose AuthActionTokenPurpose
}

func (q *Queries) GetActionTokenForUpdate(ctx context.Context, arg GetActionTokenForUpdateParams) (AuthActionToken, error) {
	row := q.db.QueryRow(ctx, getActionTokenForUpdate, arg.ID, arg.Purpose)
	var i AuthActionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RequestedIp,
		&i.CreatedAt,
	)
	return i, err
}

const invalidatePreviousActionTokens = `-- name: InvalidatePreviousActionTokens :many
UPDATE auth_action_tokens
SET consumed_at = NOW()
WHERE user_id = $1
  AND purpose = $2
  AND consumed_at IS NULL
RETURNING
    id,
    user_id,
    purpose,
    consumed_at
`

type InvalidatePreviousActionTokensParams struct {
	UserID  pgtype.UUID
	Purpose AuthActionTokenPurpose
}

type InvalidatePreviousActionTokensRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Purpose    AuthActionTokenPurpose
	ConsumedAt pgtype.Timestamptz
}

func (q *Queries) InvalidatePreviousActionTokens(ctx context.Context, arg InvalidatePreviousActionTokensParams) ([]InvalidatePreviousActionTokensRow, error) {
	rows, err := q.db.Query(ctx, invalidatePreviousActionTokens, arg.UserID, arg.Purpose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvalidatePreviousActionTokensRow{}
	for rows.Next() {
		var i InvalidatePreviousActionTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Purpose,
			&i.ConsumedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActionTokenOwner = `-- name: LockActionTokenOwner :one
SELECT u.id AS user_id
FROM auth_action_tokens AS t
JOIN users AS u ON u.id = t.user_id
WHERE t.id = $1
  AND t.purpose = $2
FOR UPDATE OF u
`

type LockActionTokenOwnerParams struct {
	ID      pgtype.UUID
	Purpose AuthActionTokenPurpose
}

func (q *Queries) LockActionTokenOwner(ctx context.Context, arg LockActionTokenOwnerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockActionTokenOwner, arg.ID, arg.Purpose)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const lockUserForActionTokenChange = `-- name: LockUserForActionTokenChange :one
SELECT id
FROM users
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockUserForActionTokenChange(ctx context.Context, userID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockUserForActionTokenChange, userID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
