// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogProductsForStore = `-- name: CountCatalogProductsForStore :one
SELECT COUNT(*)
FROM products p
INNER JOIN stores s
        ON s.organization_id = p.organization_id
       AND s.id = $1
LEFT JOIN inventory i
       ON i.organization_id = p.organization_id
      AND i.store_id = s.id
      AND i.product_id = p.id
LEFT JOIN categories c
       ON c.organization_id = p.organization_id
      AND c.id = p.category_id
WHERE p.organization_id = $2
  AND (
      CAST($3 AS TEXT) IS NULL
      OR p.name ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.sku ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.barcode ILIKE '%' || CAST($3 AS TEXT) || '%'
  )
  AND (
      CAST($4 AS UUID) IS NULL
      OR p.category_id = CAST($4 AS UUID)
  )
  AND (NOT CAST($5 AS BOOLEAN) OR p.is_active = TRUE)
  AND (
      NOT CAST($6 AS BOOLEAN)
      OR COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0
  )
`

type CountCatalogProductsForStoreParams struct {
	StoreID        pgtype.UUID
	OrganizationID pgtype.UUID
	Search         pgtype.Text
	CategoryID     pgtype.UUID
	ActiveOnly     bool
	InStockOnly    bool
}

func (q *Queries) CountCatalogProductsForStore(ctx context.Context, arg CountCatalogProductsForStoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogProductsForStore,
		arg.StoreID,
		arg.OrganizationID,
		arg.Search,
		arg.CategoryID,
		arg.ActiveOnly,
		arg.InStockOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCatalogProductByBarcodeForStore = `-- name: GetCatalogProductByBarcodeForStore :one
SELECT
    p.organization_id,
    s.id AS store_id,
    p.id,
    p.sku,
    p.barcode,
    p.name,
    p.category_id,
    c.name AS category_name,
    p.price,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) AS quantity,
    p.is_active,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0 AS in_stock,
    p.created_at,
    p.updated_at
FROM products p
INNER JOIN stores s
        ON s.organization_id = p.organization_id
       AND s.id = $1
LEFT JOIN inventory i
       ON i.organization_id = p.organization_id
      AND i.store_id = s.id
      AND i.product_id = p.id
LEFT JOIN categories c
       ON c.organization_id = p.organization_id
      AND c.id = p.category_id
WHERE p.organization_id = $2
  AND p.barcode = $3
LIMIT 1
`

type GetCatalogProductByBarcodeForStoreParams struct {
	StoreID        pgtype.UUID
	OrganizationID pgtype.UUID
	Barcode        pgtype.Text
}

type GetCatalogProductByBarcodeForStoreRow struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	CategoryName   pgtype.Text
	Price          pgtype.Numeric
	Quantity       pgtype.Numeric
	IsActive       bool
	InStock        bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCatalogProductByBarcodeForStore(ctx context.Context, arg GetCatalogProductByBarcodeForStoreParams) (GetCatalogProductByBarcodeForStoreRow, error) {
	row := q.db.QueryRow(ctx, getCatalogProductByBarcodeForStore, arg.StoreID, arg.OrganizationID, arg.Barcode)
	var i GetCatalogProductByBarcodeForStoreRow
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.Price,
		&i.Quantity,
		&i.IsActive,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogProductByIDForStore = `-- name: GetCatalogProductByIDForStore :one
SELECT
    p.organization_id,
    s.id AS store_id,
    p.id,
    p.sku,
    p.barcode,
    p.name,
    p.category_id,
    c.name AS category_name,
    p.price,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) AS quantity,
    p.is_active,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0 AS in_stock,
    p.created_at,
    p.updated_at
FROM products p
INNER JOIN stores s
        ON s.organization_id = p.organization_id
       AND s.id = $1
LEFT JOIN inventory i
       ON i.organization_id = p.organization_id
      AND i.store_id = s.id
      AND i.product_id = p.id
LEFT JOIN categories c
       ON c.organization_id = p.organization_id
      AND c.id = p.category_id
WHERE p.organization_id = $2
  AND p.id = $3
LIMIT 1
`

type GetCatalogProductByIDForStoreParams struct {
	StoreID        pgtype.UUID
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type GetCatalogProductByIDForStoreRow struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	CategoryName   pgtype.Text
	Price          pgtype.Numeric
	Quantity       pgtype.Numeric
	IsActive       bool
	InStock        bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCatalogProductByIDForStore(ctx context.Context, arg GetCatalogProductByIDForStoreParams) (GetCatalogProductByIDForStoreRow, error) {
	row := q.db.QueryRow(ctx, getCatalogProductByIDForStore, arg.StoreID, arg.OrganizationID, arg.ID)
	var i GetCatalogProductByIDForStoreRow
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.CategoryName,
		&i.Price,
		&i.Quantity,
		&i.IsActive,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCatalogProductsForStore = `-- name: ListCatalogProductsForStore :many
SELECT
    p.organization_id,
    s.id AS store_id,
    p.id,
    p.sku,
    p.barcode,
    p.name,
    p.category_id,
    c.name AS category_name,
    p.price,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) AS quantity,
    p.is_active,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0 AS in_stock,
    p.created_at,
    p.updated_at
FROM products p
INNER JOIN stores s
        ON s.organization_id = p.organization_id
       AND s.id = $1
LEFT JOIN inventory i
       ON i.organization_id = p.organization_id
      AND i.store_id = s.id
      AND i.product_id = p.id
LEFT JOIN categories c
       ON c.organization_id = p.organization_id
      AND c.id = p.category_id
WHERE p.organization_id = $2
  AND (
      CAST($3 AS TEXT) IS NULL
      OR p.name ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.sku ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.barcode ILIKE '%' || CAST($3 AS TEXT) || '%'
  )
  AND (
      CAST($4 AS UUID) IS NULL
      OR p.category_id = CAST($4 AS UUID)
  )
  AND (NOT CAST($5 AS BOOLEAN) OR p.is_active = TRUE)
  AND (
      NOT CAST($6 AS BOOLEAN)
      OR COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0
  )
ORDER BY p.name ASC, p.id ASC
LIMIT $8
OFFSET $7
`

type ListCatalogProductsForStoreParams struct {
	StoreID        pgtype.UUID
	OrganizationID pgtype.UUID
	Search         pgtype.Text
	CategoryID     pgtype.UUID
	ActiveOnly     bool
	InStockOnly    bool
	PageOffset     int32
	PageSize       int32
}

type ListCatalogProductsForStoreRow struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	CategoryName   pgtype.Text
	Price          pgtype.Numeric
	Quantity       pgtype.Numeric
	IsActive       bool
	InStock        bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListCatalogProductsForStore(ctx context.Context, arg ListCatalogProductsForStoreParams) ([]ListCatalogProductsForStoreRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProductsForStore,
		arg.StoreID,
		arg.OrganizationID,
		arg.Search,
		arg.CategoryID,
		arg.ActiveOnly,
		arg.InStockOnly,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProductsForStoreRow{}
	for rows.Next() {
		var i ListCatalogProductsForStoreRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.StoreID,
			&i.ID,
			&i.SKU,
			&i.Barcode,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.Price,
			&i.Quantity,
			&i.IsActive,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
