// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogProducts = `-- name: CountCatalogProducts :one
SELECT COUNT(*)
FROM products p
LEFT JOIN inventory i ON i.product_id = p.id
WHERE
    (
        CAST($1 AS TEXT) IS NULL
        OR p.name ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.sku ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.barcode ILIKE '%' || CAST($1 AS TEXT) || '%'
    )
    AND (NOT CAST($2 AS BOOLEAN) OR p.is_active = TRUE)
    AND (
        NOT CAST($3 AS BOOLEAN)
        OR COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0
    )
`

type CountCatalogProductsParams struct {
	Search      pgtype.Text
	ActiveOnly  bool
	InStockOnly bool
}

func (q *Queries) CountCatalogProducts(ctx context.Context, arg CountCatalogProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogProducts, arg.Search, arg.ActiveOnly, arg.InStockOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCatalogProductByBarcode = `-- name: GetCatalogProductByBarcode :one
SELECT
    p.id,
    p.sku,
    p.barcode,
    p.name,
    p.price,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) AS quantity,
    p.is_active,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0 AS in_stock,
    p.created_at,
    p.updated_at
FROM products p
LEFT JOIN inventory i ON i.product_id = p.id
WHERE p.barcode = $1
LIMIT 1
`

type GetCatalogProductByBarcodeRow struct {
	ID        pgtype.UUID
	SKU       string
	Barcode   pgtype.Text
	Name      string
	Price     pgtype.Numeric
	Quantity  pgtype.Numeric
	IsActive  bool
	InStock   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetCatalogProductByBarcode(ctx context.Context, barcode pgtype.Text) (GetCatalogProductByBarcodeRow, error) {
	row := q.db.QueryRow(ctx, getCatalogProductByBarcode, barcode)
	var i GetCatalogProductByBarcodeRow
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.IsActive,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCatalogProductByID = `-- name: GetCatalogProductByID :one
SELECT
    p.id,
    p.sku,
    p.barcode,
    p.name,
    p.price,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) AS quantity,
    p.is_active,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0 AS in_stock,
    p.created_at,
    p.updated_at
FROM products p
LEFT JOIN inventory i ON i.product_id = p.id
WHERE p.id = $1
LIMIT 1
`

type GetCatalogProductByIDRow struct {
	ID        pgtype.UUID
	SKU       string
	Barcode   pgtype.Text
	Name      string
	Price     pgtype.Numeric
	Quantity  pgtype.Numeric
	IsActive  bool
	InStock   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetCatalogProductByID(ctx context.Context, id pgtype.UUID) (GetCatalogProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getCatalogProductByID, id)
	var i GetCatalogProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Quantity,
		&i.IsActive,
		&i.InStock,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCatalogProducts = `-- name: ListCatalogProducts :many
SELECT
    p.id,
    p.sku,
    p.barcode,
    p.name,
    p.price,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) AS quantity,
    p.is_active,
    COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0 AS in_stock,
    p.created_at,
    p.updated_at
FROM products p
LEFT JOIN inventory i ON i.product_id = p.id
WHERE
    (
        CAST($1 AS TEXT) IS NULL
        OR p.name ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.sku ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.barcode ILIKE '%' || CAST($1 AS TEXT) || '%'
    )
    AND (NOT CAST($2 AS BOOLEAN) OR p.is_active = TRUE)
    AND (
        NOT CAST($3 AS BOOLEAN)
        OR COALESCE(i.quantity, CAST(0 AS NUMERIC(15, 3))) > 0
    )
ORDER BY p.name ASC, p.id ASC
LIMIT $5
OFFSET $4
`

type ListCatalogProductsParams struct {
	Search      pgtype.Text
	ActiveOnly  bool
	InStockOnly bool
	PageOffset  int32
	PageSize    int32
}

type ListCatalogProductsRow struct {
	ID        pgtype.UUID
	SKU       string
	Barcode   pgtype.Text
	Name      string
	Price     pgtype.Numeric
	Quantity  pgtype.Numeric
	IsActive  bool
	InStock   bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListCatalogProducts(ctx context.Context, arg ListCatalogProductsParams) ([]ListCatalogProductsRow, error) {
	rows, err := q.db.Query(ctx, listCatalogProducts,
		arg.Search,
		arg.ActiveOnly,
		arg.InStockOnly,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogProductsRow{}
	for rows.Next() {
		var i ListCatalogProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.SKU,
			&i.Barcode,
			&i.Name,
			&i.Price,
			&i.Quantity,
			&i.IsActive,
			&i.InStock,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
