// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateCategoryForOrganization = `-- name: ActivateCategoryForOrganization :one
UPDATE categories
SET
    is_active = TRUE,
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
RETURNING
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
`

type ActivateCategoryForOrganizationParams struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type ActivateCategoryForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ActivateCategoryForOrganization(ctx context.Context, arg ActivateCategoryForOrganizationParams) (ActivateCategoryForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, activateCategoryForOrganization, arg.OrganizationID, arg.ID)
	var i ActivateCategoryForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategoryForOrganization = `-- name: CreateCategoryForOrganization :one
INSERT INTO categories (
    organization_id,
    name,
    slug,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    TRUE
)
RETURNING
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
`

type CreateCategoryForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Name           string
	Slug           string
}

type CreateCategoryForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCategoryForOrganization(ctx context.Context, arg CreateCategoryForOrganizationParams) (CreateCategoryForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createCategoryForOrganization, arg.OrganizationID, arg.Name, arg.Slug)
	var i CreateCategoryForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCategoryForOrganization = `-- name: DeactivateCategoryForOrganization :one
UPDATE categories
SET
    is_active = FALSE,
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
RETURNING
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
`

type DeactivateCategoryForOrganizationParams struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type DeactivateCategoryForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) DeactivateCategoryForOrganization(ctx context.Context, arg DeactivateCategoryForOrganizationParams) (DeactivateCategoryForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, deactivateCategoryForOrganization, arg.OrganizationID, arg.ID)
	var i DeactivateCategoryForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByIDForOrganization = `-- name: GetCategoryByIDForOrganization :one
SELECT
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
FROM categories
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetCategoryByIDForOrganizationParams struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type GetCategoryByIDForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCategoryByIDForOrganization(ctx context.Context, arg GetCategoryByIDForOrganizationParams) (GetCategoryByIDForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByIDForOrganization, arg.OrganizationID, arg.ID)
	var i GetCategoryByIDForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByNameForOrganization = `-- name: GetCategoryByNameForOrganization :one
SELECT
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
FROM categories
WHERE organization_id = $1
  AND name = $2
LIMIT 1
`

type GetCategoryByNameForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Name           string
}

type GetCategoryByNameForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCategoryByNameForOrganization(ctx context.Context, arg GetCategoryByNameForOrganizationParams) (GetCategoryByNameForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByNameForOrganization, arg.OrganizationID, arg.Name)
	var i GetCategoryByNameForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlugForOrganization = `-- name: GetCategoryBySlugForOrganization :one
SELECT
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
FROM categories
WHERE organization_id = $1
  AND slug = $2
LIMIT 1
`

type GetCategoryBySlugForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Slug           string
}

type GetCategoryBySlugForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetCategoryBySlugForOrganization(ctx context.Context, arg GetCategoryBySlugForOrganizationParams) (GetCategoryBySlugForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlugForOrganization, arg.OrganizationID, arg.Slug)
	var i GetCategoryBySlugForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesForOrganization = `-- name: ListCategoriesForOrganization :many
SELECT
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
FROM categories
WHERE organization_id = $1
  AND (
      CAST($2 AS TEXT) IS NULL
      OR name ILIKE '%' || CAST($2 AS TEXT) || '%'
  )
  AND (NOT CAST($3 AS BOOLEAN) OR is_active = TRUE)
ORDER BY name ASC, id ASC
`

type ListCategoriesForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Search         pgtype.Text
	ActiveOnly     bool
}

type ListCategoriesForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListCategoriesForOrganization(ctx context.Context, arg ListCategoriesForOrganizationParams) ([]ListCategoriesForOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesForOrganization, arg.OrganizationID, arg.Search, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesForOrganizationRow{}
	for rows.Next() {
		var i ListCategoriesForOrganizationRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoryForOrganization = `-- name: UpdateCategoryForOrganization :one
UPDATE categories
SET
    name = $1,
    slug = $2,
    updated_at = NOW()
WHERE organization_id = $3
  AND id = $4
RETURNING
    organization_id,
    id,
    name,
    slug,
    is_active,
    created_at,
    updated_at
`

type UpdateCategoryForOrganizationParams struct {
	Name           string
	Slug           string
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type UpdateCategoryForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	Name           string
	Slug           string
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateCategoryForOrganization(ctx context.Context, arg UpdateCategoryForOrganizationParams) (UpdateCategoryForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateCategoryForOrganization,
		arg.Name,
		arg.Slug,
		arg.OrganizationID,
		arg.ID,
	)
	var i UpdateCategoryForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
