// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fiscal_documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFiscalDocument = `-- name: CreateFiscalDocument :one
WITH inserted AS (
    INSERT INTO fiscal_documents (
        sale_id,
        series,
        number,
        access_key,
        protocol,
        provider,
        external_reference,
        xml,
        error_code,
        error_message,
        issued_at,
        cancelled_at
    )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    )
    ON CONFLICT (sale_id) DO NOTHING
    RETURNING
        id,
        sale_id,
        status,
        environment,
        document_model,
        series,
        number,
        access_key,
        protocol,
        provider,
        external_reference,
        xml,
        error_code,
        error_message,
        issued_at,
        cancelled_at,
        created_at,
        updated_at
)
SELECT
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
FROM inserted
UNION ALL
SELECT
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
FROM fiscal_documents
WHERE sale_id = $1
LIMIT 1
`

type CreateFiscalDocumentParams struct {
	SaleID            pgtype.UUID
	Series            pgtype.Int4
	Number            pgtype.Int8
	AccessKey         pgtype.Text
	Protocol          pgtype.Text
	Provider          pgtype.Text
	ExternalReference pgtype.Text
	XML               pgtype.Text
	ErrorCode         pgtype.Text
	ErrorMessage      pgtype.Text
	IssuedAt          pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
}

type CreateFiscalDocumentRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	Status            FiscalDocumentStatus
	Environment       FiscalEnvironment
	DocumentModel     int16
	Series            pgtype.Int4
	Number            pgtype.Int8
	AccessKey         pgtype.Text
	Protocol          pgtype.Text
	Provider          pgtype.Text
	ExternalReference pgtype.Text
	XML               pgtype.Text
	ErrorCode         pgtype.Text
	ErrorMessage      pgtype.Text
	IssuedAt          pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateFiscalDocument(ctx context.Context, arg CreateFiscalDocumentParams) (CreateFiscalDocumentRow, error) {
	row := q.db.QueryRow(ctx, createFiscalDocument,
		arg.SaleID,
		arg.Series,
		arg.Number,
		arg.AccessKey,
		arg.Protocol,
		arg.Provider,
		arg.ExternalReference,
		arg.XML,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.IssuedAt,
		arg.CancelledAt,
	)
	var i CreateFiscalDocumentRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFiscalDocumentByID = `-- name: GetFiscalDocumentByID :one
SELECT
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
FROM fiscal_documents
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFiscalDocumentByID(ctx context.Context, id pgtype.UUID) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, getFiscalDocumentByID, id)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFiscalDocumentBySaleID = `-- name: GetFiscalDocumentBySaleID :one
SELECT
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
FROM fiscal_documents
WHERE sale_id = $1
LIMIT 1
`

func (q *Queries) GetFiscalDocumentBySaleID(ctx context.Context, saleID pgtype.UUID) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, getFiscalDocumentBySaleID, saleID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFiscalDocumentCallbacksByDocumentID = `-- name: ListFiscalDocumentCallbacksByDocumentID :many
SELECT
    id,
    fiscal_document_id,
    provider,
    callback_key,
    payload,
    received_at,
    processed_at,
    created_at,
    updated_at
FROM fiscal_document_callbacks
WHERE fiscal_document_id = $1
ORDER BY received_at DESC
`

func (q *Queries) ListFiscalDocumentCallbacksByDocumentID(ctx context.Context, fiscalDocumentID pgtype.UUID) ([]FiscalDocumentCallback, error) {
	rows, err := q.db.Query(ctx, listFiscalDocumentCallbacksByDocumentID, fiscalDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FiscalDocumentCallback{}
	for rows.Next() {
		var i FiscalDocumentCallback
		if err := rows.Scan(
			&i.ID,
			&i.FiscalDocumentID,
			&i.Provider,
			&i.CallbackKey,
			&i.Payload,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFiscalDocumentByID = `-- name: LockFiscalDocumentByID :one
SELECT
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
FROM fiscal_documents
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockFiscalDocumentByID(ctx context.Context, id pgtype.UUID) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, lockFiscalDocumentByID, id)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockFiscalDocumentBySaleID = `-- name: LockFiscalDocumentBySaleID :one
SELECT
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
FROM fiscal_documents
WHERE sale_id = $1
FOR UPDATE
`

func (q *Queries) LockFiscalDocumentBySaleID(ctx context.Context, saleID pgtype.UUID) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, lockFiscalDocumentBySaleID, saleID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentAuthorized = `-- name: MarkFiscalDocumentAuthorized :one
UPDATE fiscal_documents
SET
    status = 'AUTHORIZED',
    access_key = $1,
    protocol = $2,
    provider = $3,
    external_reference = $4,
    xml = $5,
    issued_at = COALESCE($6, NOW()),
    error_code = NULL,
    error_message = NULL
WHERE id = $7
  AND status IN ('PENDING', 'PROCESSING')
RETURNING
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
`

type MarkFiscalDocumentAuthorizedParams struct {
	AccessKey         pgtype.Text
	Protocol          pgtype.Text
	Provider          pgtype.Text
	ExternalReference pgtype.Text
	XML               pgtype.Text
	IssuedAt          pgtype.Timestamptz
	ID                pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentAuthorized(ctx context.Context, arg MarkFiscalDocumentAuthorizedParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentAuthorized,
		arg.AccessKey,
		arg.Protocol,
		arg.Provider,
		arg.ExternalReference,
		arg.XML,
		arg.IssuedAt,
		arg.ID,
	)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentCallbackProcessed = `-- name: MarkFiscalDocumentCallbackProcessed :one
UPDATE fiscal_document_callbacks
SET processed_at = COALESCE($1, NOW())
WHERE id = $2
RETURNING
    id,
    fiscal_document_id,
    provider,
    callback_key,
    payload,
    received_at,
    processed_at,
    created_at,
    updated_at
`

type MarkFiscalDocumentCallbackProcessedParams struct {
	ProcessedAt pgtype.Timestamptz
	ID          pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentCallbackProcessed(ctx context.Context, arg MarkFiscalDocumentCallbackProcessedParams) (FiscalDocumentCallback, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentCallbackProcessed, arg.ProcessedAt, arg.ID)
	var i FiscalDocumentCallback
	err := row.Scan(
		&i.ID,
		&i.FiscalDocumentID,
		&i.Provider,
		&i.CallbackKey,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentCancelled = `-- name: MarkFiscalDocumentCancelled :one
UPDATE fiscal_documents
SET
    status = 'CANCELLED',
    cancelled_at = COALESCE($1, NOW())
WHERE id = $2
  AND status IN ('PENDING', 'PROCESSING', 'AUTHORIZED', 'REJECTED', 'ERROR')
RETURNING
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
`

type MarkFiscalDocumentCancelledParams struct {
	CancelledAt pgtype.Timestamptz
	ID          pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentCancelled(ctx context.Context, arg MarkFiscalDocumentCancelledParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentCancelled, arg.CancelledAt, arg.ID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentError = `-- name: MarkFiscalDocumentError :one
UPDATE fiscal_documents
SET
    status = 'ERROR',
    error_code = $1,
    error_message = $2
WHERE id = $3
  AND status IN ('PENDING', 'PROCESSING', 'REJECTED')
RETURNING
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
`

type MarkFiscalDocumentErrorParams struct {
	ErrorCode    pgtype.Text
	ErrorMessage pgtype.Text
	ID           pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentError(ctx context.Context, arg MarkFiscalDocumentErrorParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentError, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentProcessing = `-- name: MarkFiscalDocumentProcessing :one
UPDATE fiscal_documents
SET status = 'PROCESSING'
WHERE id = $1
  AND status = 'PENDING'
RETURNING
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
`

func (q *Queries) MarkFiscalDocumentProcessing(ctx context.Context, id pgtype.UUID) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentProcessing, id)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentRejected = `-- name: MarkFiscalDocumentRejected :one
UPDATE fiscal_documents
SET
    status = 'REJECTED',
    error_code = $1,
    error_message = $2
WHERE id = $3
  AND status IN ('PENDING', 'PROCESSING', 'ERROR')
RETURNING
    id,
    sale_id,
    status,
    environment,
    document_model,
    series,
    number,
    access_key,
    protocol,
    provider,
    external_reference,
    xml,
    error_code,
    error_message,
    issued_at,
    cancelled_at,
    created_at,
    updated_at
`

type MarkFiscalDocumentRejectedParams struct {
	ErrorCode    pgtype.Text
	ErrorMessage pgtype.Text
	ID           pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentRejected(ctx context.Context, arg MarkFiscalDocumentRejectedParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentRejected, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFiscalDocumentCallback = `-- name: UpsertFiscalDocumentCallback :one
WITH inserted AS (
    INSERT INTO fiscal_document_callbacks (
        fiscal_document_id,
        provider,
        callback_key,
        payload,
        received_at,
        processed_at
    )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        COALESCE($5, NOW()),
        $6
    )
    ON CONFLICT (provider, callback_key) DO UPDATE
    SET
        payload = EXCLUDED.payload,
        processed_at = COALESCE(fiscal_document_callbacks.processed_at, EXCLUDED.processed_at),
        updated_at = NOW()
    RETURNING
        id,
        fiscal_document_id,
        provider,
        callback_key,
        payload,
        received_at,
        processed_at,
        created_at,
        updated_at
)
SELECT
    id,
    fiscal_document_id,
    provider,
    callback_key,
    payload,
    received_at,
    processed_at,
    created_at,
    updated_at
FROM inserted
LIMIT 1
`

type UpsertFiscalDocumentCallbackParams struct {
	FiscalDocumentID pgtype.UUID
	Provider         string
	CallbackKey      string
	Payload          string
	ReceivedAt       interface{}
	ProcessedAt      pgtype.Timestamptz
}

type UpsertFiscalDocumentCallbackRow struct {
	ID               pgtype.UUID
	FiscalDocumentID pgtype.UUID
	Provider         string
	CallbackKey      string
	Payload          string
	ReceivedAt       pgtype.Timestamptz
	ProcessedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpsertFiscalDocumentCallback(ctx context.Context, arg UpsertFiscalDocumentCallbackParams) (UpsertFiscalDocumentCallbackRow, error) {
	row := q.db.QueryRow(ctx, upsertFiscalDocumentCallback,
		arg.FiscalDocumentID,
		arg.Provider,
		arg.CallbackKey,
		arg.Payload,
		arg.ReceivedAt,
		arg.ProcessedAt,
	)
	var i UpsertFiscalDocumentCallbackRow
	err := row.Scan(
		&i.ID,
		&i.FiscalDocumentID,
		&i.Provider,
		&i.CallbackKey,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
