// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fiscal_documents.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFiscalDocumentCallbacksByDocumentIDForStore = `-- name: CountFiscalDocumentCallbacksByDocumentIDForStore :one
SELECT COUNT(*)
FROM fiscal_document_callbacks AS callback
WHERE callback.organization_id = $1
  AND callback.store_id = $2
  AND callback.fiscal_document_id = $3
`

type CountFiscalDocumentCallbacksByDocumentIDForStoreParams struct {
	OrganizationID   pgtype.UUID
	StoreID          pgtype.UUID
	FiscalDocumentID pgtype.UUID
}

func (q *Queries) CountFiscalDocumentCallbacksByDocumentIDForStore(ctx context.Context, arg CountFiscalDocumentCallbacksByDocumentIDForStoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFiscalDocumentCallbacksByDocumentIDForStore, arg.OrganizationID, arg.StoreID, arg.FiscalDocumentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFiscalDocumentForStore = `-- name: CreateFiscalDocumentForStore :one
WITH inserted AS (
    INSERT INTO fiscal_documents (
        organization_id,
        store_id,
        sale_id,
        series,
        number,
        access_key,
        protocol,
        provider,
        external_reference,
        xml,
        error_code,
        error_message,
        issued_at,
        cancelled_at
    )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14
    )
    ON CONFLICT (organization_id, store_id, sale_id) DO UPDATE
    SET sale_id = EXCLUDED.sale_id
    RETURNING
        id,
        organization_id,
        store_id,
        sale_id,
        status,
        environment,
        document_model,
        series,
        number,
        access_key,
        protocol,
        provider,
        external_reference,
        xml,
        error_code,
        error_message,
        issued_at,
        cancelled_at,
        created_at,
        updated_at
)
SELECT id, organization_id, store_id, sale_id, status, environment, document_model, series, number, access_key, protocol, provider, external_reference, xml, error_code, error_message, issued_at, cancelled_at, created_at, updated_at FROM inserted
UNION ALL
SELECT
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
FROM fiscal_documents AS document
WHERE document.organization_id = $1
  AND document.store_id = $2
  AND document.sale_id = $3
LIMIT 1
`

type CreateFiscalDocumentForStoreParams struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	SaleID            pgtype.UUID
	Series            pgtype.Int4
	Number            pgtype.Int8
	AccessKey         pgtype.Text
	Protocol          pgtype.Text
	Provider          pgtype.Text
	ExternalReference pgtype.Text
	XML               pgtype.Text
	ErrorCode         pgtype.Text
	ErrorMessage      pgtype.Text
	IssuedAt          pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
}

type CreateFiscalDocumentForStoreRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	SaleID            pgtype.UUID
	Status            FiscalDocumentStatus
	Environment       FiscalEnvironment
	DocumentModel     int16
	Series            pgtype.Int4
	Number            pgtype.Int8
	AccessKey         pgtype.Text
	Protocol          pgtype.Text
	Provider          pgtype.Text
	ExternalReference pgtype.Text
	XML               pgtype.Text
	ErrorCode         pgtype.Text
	ErrorMessage      pgtype.Text
	IssuedAt          pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateFiscalDocumentForStore(ctx context.Context, arg CreateFiscalDocumentForStoreParams) (CreateFiscalDocumentForStoreRow, error) {
	row := q.db.QueryRow(ctx, createFiscalDocumentForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.SaleID,
		arg.Series,
		arg.Number,
		arg.AccessKey,
		arg.Protocol,
		arg.Provider,
		arg.ExternalReference,
		arg.XML,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.IssuedAt,
		arg.CancelledAt,
	)
	var i CreateFiscalDocumentForStoreRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFiscalDocumentByIDForStore = `-- name: GetFiscalDocumentByIDForStore :one
SELECT
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
FROM fiscal_documents AS document
WHERE document.organization_id = $1
  AND document.store_id = $2
  AND document.id = $3
LIMIT 1
`

type GetFiscalDocumentByIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) GetFiscalDocumentByIDForStore(ctx context.Context, arg GetFiscalDocumentByIDForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, getFiscalDocumentByIDForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFiscalDocumentBySaleIDForStore = `-- name: GetFiscalDocumentBySaleIDForStore :one
SELECT
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
FROM fiscal_documents AS document
WHERE document.organization_id = $1
  AND document.store_id = $2
  AND document.sale_id = $3
LIMIT 1
`

type GetFiscalDocumentBySaleIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	SaleID         pgtype.UUID
}

func (q *Queries) GetFiscalDocumentBySaleIDForStore(ctx context.Context, arg GetFiscalDocumentBySaleIDForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, getFiscalDocumentBySaleIDForStore, arg.OrganizationID, arg.StoreID, arg.SaleID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFiscalDocumentCallbacksByDocumentIDForStore = `-- name: ListFiscalDocumentCallbacksByDocumentIDForStore :many
SELECT
    callback.id,
    callback.organization_id,
    callback.store_id,
    callback.fiscal_document_id,
    callback.provider,
    callback.callback_key,
    callback.payload,
    callback.received_at,
    callback.processed_at,
    callback.created_at,
    callback.updated_at
FROM fiscal_document_callbacks AS callback
WHERE callback.organization_id = $1
  AND callback.store_id = $2
  AND callback.fiscal_document_id = $3
ORDER BY callback.received_at DESC, callback.id DESC
`

type ListFiscalDocumentCallbacksByDocumentIDForStoreParams struct {
	OrganizationID   pgtype.UUID
	StoreID          pgtype.UUID
	FiscalDocumentID pgtype.UUID
}

func (q *Queries) ListFiscalDocumentCallbacksByDocumentIDForStore(ctx context.Context, arg ListFiscalDocumentCallbacksByDocumentIDForStoreParams) ([]FiscalDocumentCallback, error) {
	rows, err := q.db.Query(ctx, listFiscalDocumentCallbacksByDocumentIDForStore, arg.OrganizationID, arg.StoreID, arg.FiscalDocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FiscalDocumentCallback{}
	for rows.Next() {
		var i FiscalDocumentCallback
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.FiscalDocumentID,
			&i.Provider,
			&i.CallbackKey,
			&i.Payload,
			&i.ReceivedAt,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFiscalDocumentByIDForStore = `-- name: LockFiscalDocumentByIDForStore :one
SELECT
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
FROM fiscal_documents AS document
WHERE document.organization_id = $1
  AND document.store_id = $2
  AND document.id = $3
FOR UPDATE
`

type LockFiscalDocumentByIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) LockFiscalDocumentByIDForStore(ctx context.Context, arg LockFiscalDocumentByIDForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, lockFiscalDocumentByIDForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockFiscalDocumentBySaleIDForStore = `-- name: LockFiscalDocumentBySaleIDForStore :one
SELECT
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
FROM fiscal_documents AS document
WHERE document.organization_id = $1
  AND document.store_id = $2
  AND document.sale_id = $3
FOR UPDATE
`

type LockFiscalDocumentBySaleIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	SaleID         pgtype.UUID
}

func (q *Queries) LockFiscalDocumentBySaleIDForStore(ctx context.Context, arg LockFiscalDocumentBySaleIDForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, lockFiscalDocumentBySaleIDForStore, arg.OrganizationID, arg.StoreID, arg.SaleID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockFiscalDocumentCallbackByIDForStore = `-- name: LockFiscalDocumentCallbackByIDForStore :one
SELECT
    callback.id,
    callback.organization_id,
    callback.store_id,
    callback.fiscal_document_id,
    callback.provider,
    callback.callback_key,
    callback.payload,
    callback.received_at,
    callback.processed_at,
    callback.created_at,
    callback.updated_at
FROM fiscal_document_callbacks AS callback
WHERE callback.organization_id = $1
  AND callback.store_id = $2
  AND callback.id = $3
FOR UPDATE
`

type LockFiscalDocumentCallbackByIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) LockFiscalDocumentCallbackByIDForStore(ctx context.Context, arg LockFiscalDocumentCallbackByIDForStoreParams) (FiscalDocumentCallback, error) {
	row := q.db.QueryRow(ctx, lockFiscalDocumentCallbackByIDForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i FiscalDocumentCallback
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.FiscalDocumentID,
		&i.Provider,
		&i.CallbackKey,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentAuthorizedForStore = `-- name: MarkFiscalDocumentAuthorizedForStore :one
UPDATE fiscal_documents AS document
SET
    status = 'AUTHORIZED',
    access_key = $1,
    protocol = $2,
    provider = $3,
    external_reference = $4,
    xml = $5,
    issued_at = COALESCE($6, NOW()),
    error_code = NULL,
    error_message = NULL
WHERE document.organization_id = $7
  AND document.store_id = $8
  AND document.id = $9
  AND document.status IN ('PENDING', 'PROCESSING')
RETURNING
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
`

type MarkFiscalDocumentAuthorizedForStoreParams struct {
	AccessKey         pgtype.Text
	Protocol          pgtype.Text
	Provider          pgtype.Text
	ExternalReference pgtype.Text
	XML               pgtype.Text
	IssuedAt          pgtype.Timestamptz
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ID                pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentAuthorizedForStore(ctx context.Context, arg MarkFiscalDocumentAuthorizedForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentAuthorizedForStore,
		arg.AccessKey,
		arg.Protocol,
		arg.Provider,
		arg.ExternalReference,
		arg.XML,
		arg.IssuedAt,
		arg.OrganizationID,
		arg.StoreID,
		arg.ID,
	)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentCallbackProcessedForStore = `-- name: MarkFiscalDocumentCallbackProcessedForStore :one
UPDATE fiscal_document_callbacks AS callback
SET processed_at = COALESCE($1, NOW())
WHERE callback.organization_id = $2
  AND callback.store_id = $3
  AND callback.id = $4
RETURNING
    callback.id,
    callback.organization_id,
    callback.store_id,
    callback.fiscal_document_id,
    callback.provider,
    callback.callback_key,
    callback.payload,
    callback.received_at,
    callback.processed_at,
    callback.created_at,
    callback.updated_at
`

type MarkFiscalDocumentCallbackProcessedForStoreParams struct {
	ProcessedAt    pgtype.Timestamptz
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentCallbackProcessedForStore(ctx context.Context, arg MarkFiscalDocumentCallbackProcessedForStoreParams) (FiscalDocumentCallback, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentCallbackProcessedForStore,
		arg.ProcessedAt,
		arg.OrganizationID,
		arg.StoreID,
		arg.ID,
	)
	var i FiscalDocumentCallback
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.FiscalDocumentID,
		&i.Provider,
		&i.CallbackKey,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentCancelledForStore = `-- name: MarkFiscalDocumentCancelledForStore :one
UPDATE fiscal_documents AS document
SET
    status = 'CANCELLED',
    cancelled_at = COALESCE($1, NOW())
WHERE document.organization_id = $2
  AND document.store_id = $3
  AND document.id = $4
  AND document.status IN ('PENDING', 'PROCESSING', 'AUTHORIZED', 'REJECTED', 'ERROR')
  AND document.access_key IS NOT NULL
  AND document.protocol IS NOT NULL
  AND document.issued_at IS NOT NULL
RETURNING
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
`

type MarkFiscalDocumentCancelledForStoreParams struct {
	CancelledAt    pgtype.Timestamptz
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentCancelledForStore(ctx context.Context, arg MarkFiscalDocumentCancelledForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentCancelledForStore,
		arg.CancelledAt,
		arg.OrganizationID,
		arg.StoreID,
		arg.ID,
	)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentErrorForStore = `-- name: MarkFiscalDocumentErrorForStore :one
UPDATE fiscal_documents AS document
SET
    status = 'ERROR',
    error_code = $1,
    error_message = $2
WHERE document.organization_id = $3
  AND document.store_id = $4
  AND document.id = $5
  AND document.status IN ('PENDING', 'PROCESSING', 'REJECTED')
RETURNING
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
`

type MarkFiscalDocumentErrorForStoreParams struct {
	ErrorCode      pgtype.Text
	ErrorMessage   pgtype.Text
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentErrorForStore(ctx context.Context, arg MarkFiscalDocumentErrorForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentErrorForStore,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OrganizationID,
		arg.StoreID,
		arg.ID,
	)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentProcessingForStore = `-- name: MarkFiscalDocumentProcessingForStore :one
UPDATE fiscal_documents AS document
SET status = 'PROCESSING'
WHERE document.organization_id = $1
  AND document.store_id = $2
  AND document.id = $3
  AND document.status IN ('PENDING', 'REJECTED', 'ERROR')
RETURNING
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
`

type MarkFiscalDocumentProcessingForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentProcessingForStore(ctx context.Context, arg MarkFiscalDocumentProcessingForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentProcessingForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markFiscalDocumentRejectedForStore = `-- name: MarkFiscalDocumentRejectedForStore :one
UPDATE fiscal_documents AS document
SET
    status = 'REJECTED',
    error_code = $1,
    error_message = $2
WHERE document.organization_id = $3
  AND document.store_id = $4
  AND document.id = $5
  AND document.status IN ('PENDING', 'PROCESSING', 'ERROR')
RETURNING
    document.id,
    document.organization_id,
    document.store_id,
    document.sale_id,
    document.status,
    document.environment,
    document.document_model,
    document.series,
    document.number,
    document.access_key,
    document.protocol,
    document.provider,
    document.external_reference,
    document.xml,
    document.error_code,
    document.error_message,
    document.issued_at,
    document.cancelled_at,
    document.created_at,
    document.updated_at
`

type MarkFiscalDocumentRejectedForStoreParams struct {
	ErrorCode      pgtype.Text
	ErrorMessage   pgtype.Text
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) MarkFiscalDocumentRejectedForStore(ctx context.Context, arg MarkFiscalDocumentRejectedForStoreParams) (FiscalDocument, error) {
	row := q.db.QueryRow(ctx, markFiscalDocumentRejectedForStore,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OrganizationID,
		arg.StoreID,
		arg.ID,
	)
	var i FiscalDocument
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.Status,
		&i.Environment,
		&i.DocumentModel,
		&i.Series,
		&i.Number,
		&i.AccessKey,
		&i.Protocol,
		&i.Provider,
		&i.ExternalReference,
		&i.XML,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.IssuedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFiscalDocumentCallbackForStore = `-- name: UpsertFiscalDocumentCallbackForStore :one
INSERT INTO fiscal_document_callbacks (
    organization_id,
    store_id,
    fiscal_document_id,
    provider,
    callback_key,
    payload,
    received_at,
    processed_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
        COALESCE(CAST($7 AS TIMESTAMPTZ), NOW()),
    $8
)
ON CONFLICT (provider, callback_key) DO UPDATE
SET
    payload = EXCLUDED.payload,
    processed_at = COALESCE(fiscal_document_callbacks.processed_at, EXCLUDED.processed_at)
WHERE fiscal_document_callbacks.organization_id = EXCLUDED.organization_id
  AND fiscal_document_callbacks.store_id = EXCLUDED.store_id
  AND fiscal_document_callbacks.fiscal_document_id = EXCLUDED.fiscal_document_id
RETURNING
    id,
    organization_id,
    store_id,
    fiscal_document_id,
    provider,
    callback_key,
    payload,
    received_at,
    processed_at,
    created_at,
    updated_at
`

type UpsertFiscalDocumentCallbackForStoreParams struct {
	OrganizationID   pgtype.UUID
	StoreID          pgtype.UUID
	FiscalDocumentID pgtype.UUID
	Provider         string
	CallbackKey      string
	Payload          string
	ReceivedAt       pgtype.Timestamptz
	ProcessedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertFiscalDocumentCallbackForStore(ctx context.Context, arg UpsertFiscalDocumentCallbackForStoreParams) (FiscalDocumentCallback, error) {
	row := q.db.QueryRow(ctx, upsertFiscalDocumentCallbackForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.FiscalDocumentID,
		arg.Provider,
		arg.CallbackKey,
		arg.Payload,
		arg.ReceivedAt,
		arg.ProcessedAt,
	)
	var i FiscalDocumentCallback
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.FiscalDocumentID,
		&i.Provider,
		&i.CallbackKey,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
