// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInventoryForStore = `-- name: CountInventoryForStore :one
SELECT COUNT(*)
FROM inventory i
INNER JOIN products p
        ON p.organization_id = i.organization_id
       AND p.id = i.product_id
WHERE i.organization_id = $1
  AND i.store_id = $2
  AND (
      CAST($3 AS TEXT) IS NULL
      OR p.name ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.sku ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.barcode ILIKE '%' || CAST($3 AS TEXT) || '%'
  )
  AND (NOT CAST($4 AS BOOLEAN) OR p.is_active = TRUE)
`

type CountInventoryForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	Search         pgtype.Text
	ActiveOnly     bool
}

func (q *Queries) CountInventoryForStore(ctx context.Context, arg CountInventoryForStoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.Search,
		arg.ActiveOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInventoryMovementsByProductIDForStore = `-- name: CountInventoryMovementsByProductIDForStore :one
SELECT COUNT(*)
FROM inventory_movements
WHERE organization_id = $1
  AND store_id = $2
  AND product_id = $3
  AND (
      CAST($4 AS inventory_movement_type) IS NULL
      OR movement_type = CAST($4 AS inventory_movement_type)
  )
`

type CountInventoryMovementsByProductIDForStoreParams struct {
	OrganizationID     pgtype.UUID
	StoreID            pgtype.UUID
	ProductID          pgtype.UUID
	MovementTypeFilter NullInventoryMovementType
}

func (q *Queries) CountInventoryMovementsByProductIDForStore(ctx context.Context, arg CountInventoryMovementsByProductIDForStoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryMovementsByProductIDForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.ProductID,
		arg.MovementTypeFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryMovementForStore = `-- name: CreateInventoryMovementForStore :one
INSERT INTO inventory_movements (
    organization_id,
    store_id,
    product_id,
    actor_membership_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING
    organization_id,
    store_id,
    id,
    product_id,
    actor_membership_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id,
    created_at
`

type CreateInventoryMovementForStoreParams struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ProductID         pgtype.UUID
	ActorMembershipID pgtype.UUID
	MovementType      InventoryMovementType
	Quantity          pgtype.Numeric
	PreviousQuantity  pgtype.Numeric
	CurrentQuantity   pgtype.Numeric
	Reason            pgtype.Text
	ReferenceType     string
	ReferenceID       pgtype.UUID
}

type CreateInventoryMovementForStoreRow struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ID                pgtype.UUID
	ProductID         pgtype.UUID
	ActorMembershipID pgtype.UUID
	MovementType      InventoryMovementType
	Quantity          pgtype.Numeric
	PreviousQuantity  pgtype.Numeric
	CurrentQuantity   pgtype.Numeric
	Reason            pgtype.Text
	ReferenceType     string
	ReferenceID       pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) CreateInventoryMovementForStore(ctx context.Context, arg CreateInventoryMovementForStoreParams) (CreateInventoryMovementForStoreRow, error) {
	row := q.db.QueryRow(ctx, createInventoryMovementForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.ProductID,
		arg.ActorMembershipID,
		arg.MovementType,
		arg.Quantity,
		arg.PreviousQuantity,
		arg.CurrentQuantity,
		arg.Reason,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i CreateInventoryMovementForStoreRow
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ID,
		&i.ProductID,
		&i.ActorMembershipID,
		&i.MovementType,
		&i.Quantity,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseInventoryForStore = `-- name: DecreaseInventoryForStore :one
UPDATE inventory
SET
    quantity = quantity - $1,
    updated_at = NOW()
WHERE organization_id = $2
  AND store_id = $3
  AND product_id = $4
  AND $1::NUMERIC > 0
  AND quantity >= $1
RETURNING
    organization_id,
    store_id,
    product_id,
    CAST(quantity + $1 AS NUMERIC(15, 3)) AS previous_quantity,
    quantity AS current_quantity,
    created_at,
    updated_at
`

type DecreaseInventoryForStoreParams struct {
	Quantity       pgtype.Numeric
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ProductID      pgtype.UUID
}

type DecreaseInventoryForStoreRow struct {
	OrganizationID   pgtype.UUID
	StoreID          pgtype.UUID
	ProductID        pgtype.UUID
	PreviousQuantity pgtype.Numeric
	CurrentQuantity  pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) DecreaseInventoryForStore(ctx context.Context, arg DecreaseInventoryForStoreParams) (DecreaseInventoryForStoreRow, error) {
	row := q.db.QueryRow(ctx, decreaseInventoryForStore,
		arg.Quantity,
		arg.OrganizationID,
		arg.StoreID,
		arg.ProductID,
	)
	var i DecreaseInventoryForStoreRow
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ProductID,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryByProductIDForStore = `-- name: GetInventoryByProductIDForStore :one
SELECT
    organization_id,
    store_id,
    product_id,
    quantity,
    created_at,
    updated_at
FROM inventory
WHERE organization_id = $1
  AND store_id = $2
  AND product_id = $3
LIMIT 1
`

type GetInventoryByProductIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ProductID      pgtype.UUID
}

func (q *Queries) GetInventoryByProductIDForStore(ctx context.Context, arg GetInventoryByProductIDForStoreParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByProductIDForStore, arg.OrganizationID, arg.StoreID, arg.ProductID)
	var i Inventory
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryMovementByReferenceForStore = `-- name: GetInventoryMovementByReferenceForStore :one
SELECT
    organization_id,
    store_id,
    id,
    product_id,
    actor_membership_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id,
    created_at
FROM inventory_movements
WHERE organization_id = $1
  AND store_id = $2
  AND product_id = $3
  AND movement_type = $4
  AND reference_type = $5
  AND reference_id = $6
LIMIT 1
`

type GetInventoryMovementByReferenceForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ProductID      pgtype.UUID
	MovementType   InventoryMovementType
	ReferenceType  string
	ReferenceID    pgtype.UUID
}

type GetInventoryMovementByReferenceForStoreRow struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ID                pgtype.UUID
	ProductID         pgtype.UUID
	ActorMembershipID pgtype.UUID
	MovementType      InventoryMovementType
	Quantity          pgtype.Numeric
	PreviousQuantity  pgtype.Numeric
	CurrentQuantity   pgtype.Numeric
	Reason            pgtype.Text
	ReferenceType     string
	ReferenceID       pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) GetInventoryMovementByReferenceForStore(ctx context.Context, arg GetInventoryMovementByReferenceForStoreParams) (GetInventoryMovementByReferenceForStoreRow, error) {
	row := q.db.QueryRow(ctx, getInventoryMovementByReferenceForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.ProductID,
		arg.MovementType,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i GetInventoryMovementByReferenceForStoreRow
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ID,
		&i.ProductID,
		&i.ActorMembershipID,
		&i.MovementType,
		&i.Quantity,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const increaseInventoryForStore = `-- name: IncreaseInventoryForStore :one
INSERT INTO inventory (
    organization_id,
    store_id,
    product_id,
    quantity
)
SELECT
    $1,
    $2,
    $3,
    $4
WHERE $4::NUMERIC > 0
ON CONFLICT (organization_id, store_id, product_id)
DO UPDATE SET
    quantity = inventory.quantity + EXCLUDED.quantity,
    updated_at = NOW()
RETURNING
    organization_id,
    store_id,
    product_id,
    CAST(quantity - $4 AS NUMERIC(15, 3)) AS previous_quantity,
    quantity AS current_quantity,
    created_at,
    updated_at
`

type IncreaseInventoryForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ProductID      pgtype.UUID
	Quantity       pgtype.Numeric
}

type IncreaseInventoryForStoreRow struct {
	OrganizationID   pgtype.UUID
	StoreID          pgtype.UUID
	ProductID        pgtype.UUID
	PreviousQuantity pgtype.Numeric
	CurrentQuantity  pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) IncreaseInventoryForStore(ctx context.Context, arg IncreaseInventoryForStoreParams) (IncreaseInventoryForStoreRow, error) {
	row := q.db.QueryRow(ctx, increaseInventoryForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.ProductID,
		arg.Quantity,
	)
	var i IncreaseInventoryForStoreRow
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ProductID,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventoryForStore = `-- name: ListInventoryForStore :many
SELECT
    i.organization_id,
    i.store_id,
    p.id AS product_id,
    p.sku,
    p.barcode,
    p.name,
    p.is_active,
    i.quantity,
    i.created_at,
    i.updated_at
FROM inventory i
INNER JOIN products p
        ON p.organization_id = i.organization_id
       AND p.id = i.product_id
WHERE i.organization_id = $1
  AND i.store_id = $2
  AND (
      CAST($3 AS TEXT) IS NULL
      OR p.name ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.sku ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR p.barcode ILIKE '%' || CAST($3 AS TEXT) || '%'
  )
  AND (NOT CAST($4 AS BOOLEAN) OR p.is_active = TRUE)
ORDER BY p.name ASC, p.id ASC
LIMIT $6
OFFSET $5
`

type ListInventoryForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	Search         pgtype.Text
	ActiveOnly     bool
	PageOffset     int32
	PageSize       int32
}

type ListInventoryForStoreRow struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ProductID      pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	IsActive       bool
	Quantity       pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListInventoryForStore(ctx context.Context, arg ListInventoryForStoreParams) ([]ListInventoryForStoreRow, error) {
	rows, err := q.db.Query(ctx, listInventoryForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.Search,
		arg.ActiveOnly,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryForStoreRow{}
	for rows.Next() {
		var i ListInventoryForStoreRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.StoreID,
			&i.ProductID,
			&i.SKU,
			&i.Barcode,
			&i.Name,
			&i.IsActive,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryMovementsByProductIDForStore = `-- name: ListInventoryMovementsByProductIDForStore :many
SELECT
    organization_id,
    store_id,
    id,
    product_id,
    actor_membership_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id,
    created_at
FROM inventory_movements
WHERE organization_id = $1
  AND store_id = $2
  AND product_id = $3
  AND (
      CAST($4 AS inventory_movement_type) IS NULL
      OR movement_type = CAST($4 AS inventory_movement_type)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
OFFSET $5
`

type ListInventoryMovementsByProductIDForStoreParams struct {
	OrganizationID     pgtype.UUID
	StoreID            pgtype.UUID
	ProductID          pgtype.UUID
	MovementTypeFilter NullInventoryMovementType
	PageOffset         int32
	PageSize           int32
}

type ListInventoryMovementsByProductIDForStoreRow struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	ID                pgtype.UUID
	ProductID         pgtype.UUID
	ActorMembershipID pgtype.UUID
	MovementType      InventoryMovementType
	Quantity          pgtype.Numeric
	PreviousQuantity  pgtype.Numeric
	CurrentQuantity   pgtype.Numeric
	Reason            pgtype.Text
	ReferenceType     string
	ReferenceID       pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ListInventoryMovementsByProductIDForStore(ctx context.Context, arg ListInventoryMovementsByProductIDForStoreParams) ([]ListInventoryMovementsByProductIDForStoreRow, error) {
	rows, err := q.db.Query(ctx, listInventoryMovementsByProductIDForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.ProductID,
		arg.MovementTypeFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryMovementsByProductIDForStoreRow{}
	for rows.Next() {
		var i ListInventoryMovementsByProductIDForStoreRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.StoreID,
			&i.ID,
			&i.ProductID,
			&i.ActorMembershipID,
			&i.MovementType,
			&i.Quantity,
			&i.PreviousQuantity,
			&i.CurrentQuantity,
			&i.Reason,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
