// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInventory = `-- name: CountInventory :one
SELECT COUNT(*)
FROM inventory i
INNER JOIN products p ON p.id = i.product_id
WHERE
    (
        CAST($1 AS TEXT) IS NULL
        OR p.name ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.sku ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.barcode ILIKE '%' || CAST($1 AS TEXT) || '%'
    )
    AND (NOT $2 OR p.is_active = TRUE)
`

type CountInventoryParams struct {
	Search     pgtype.Text
	ActiveOnly interface{}
}

func (q *Queries) CountInventory(ctx context.Context, arg CountInventoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventory, arg.Search, arg.ActiveOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInventoryMovementsByProductID = `-- name: CountInventoryMovementsByProductID :one
SELECT COUNT(*)
FROM inventory_movements
WHERE product_id = $1
  AND (
      CAST($2 AS inventory_movement_type) IS NULL
      OR movement_type = CAST($2 AS inventory_movement_type)
  )
`

type CountInventoryMovementsByProductIDParams struct {
	ProductID          pgtype.UUID
	MovementTypeFilter NullInventoryMovementType
}

func (q *Queries) CountInventoryMovementsByProductID(ctx context.Context, arg CountInventoryMovementsByProductIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInventoryMovementsByProductID, arg.ProductID, arg.MovementTypeFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements (
    product_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    product_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id,
    created_at
`

type CreateInventoryMovementParams struct {
	ProductID        pgtype.UUID
	MovementType     InventoryMovementType
	Quantity         pgtype.Numeric
	PreviousQuantity pgtype.Numeric
	CurrentQuantity  pgtype.Numeric
	Reason           pgtype.Text
	ReferenceType    string
	ReferenceID      pgtype.UUID
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.ProductID,
		arg.MovementType,
		arg.Quantity,
		arg.PreviousQuantity,
		arg.CurrentQuantity,
		arg.Reason,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.MovementType,
		&i.Quantity,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const decreaseInventory = `-- name: DecreaseInventory :one
UPDATE inventory
SET
    quantity = quantity - $1,
    updated_at = NOW()
WHERE product_id = $2
  AND quantity >= $1
RETURNING
    product_id,
    CAST(quantity + $1 AS NUMERIC(15, 3)) AS previous_quantity,
    quantity AS current_quantity,
    created_at,
    updated_at
`

type DecreaseInventoryParams struct {
	Quantity  pgtype.Numeric
	ProductID pgtype.UUID
}

type DecreaseInventoryRow struct {
	ProductID        pgtype.UUID
	PreviousQuantity pgtype.Numeric
	CurrentQuantity  pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) DecreaseInventory(ctx context.Context, arg DecreaseInventoryParams) (DecreaseInventoryRow, error) {
	row := q.db.QueryRow(ctx, decreaseInventory, arg.Quantity, arg.ProductID)
	var i DecreaseInventoryRow
	err := row.Scan(
		&i.ProductID,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryByProductID = `-- name: GetInventoryByProductID :one
SELECT
    product_id,
    quantity,
    created_at,
    updated_at
FROM inventory
WHERE product_id = $1
LIMIT 1
`

func (q *Queries) GetInventoryByProductID(ctx context.Context, productID pgtype.UUID) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryByProductID, productID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInventoryMovementByReference = `-- name: GetInventoryMovementByReference :one
SELECT
    id,
    product_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id,
    created_at
FROM inventory_movements
WHERE product_id = $1
  AND movement_type = $2
  AND reference_type = $3
  AND reference_id = $4
LIMIT 1
`

type GetInventoryMovementByReferenceParams struct {
	ProductID     pgtype.UUID
	MovementType  InventoryMovementType
	ReferenceType string
	ReferenceID   pgtype.UUID
}

func (q *Queries) GetInventoryMovementByReference(ctx context.Context, arg GetInventoryMovementByReferenceParams) (InventoryMovement, error) {
	row := q.db.QueryRow(ctx, getInventoryMovementByReference,
		arg.ProductID,
		arg.MovementType,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.MovementType,
		&i.Quantity,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const increaseInventory = `-- name: IncreaseInventory :one
INSERT INTO inventory (
    product_id,
    quantity
)
VALUES (
    $1,
    $2
)
ON CONFLICT (product_id)
DO UPDATE SET
    quantity = inventory.quantity + EXCLUDED.quantity,
    updated_at = NOW()
RETURNING
    product_id,
    CAST(quantity - $2 AS NUMERIC(15, 3)) AS previous_quantity,
    quantity AS current_quantity,
    created_at,
    updated_at
`

type IncreaseInventoryParams struct {
	ProductID pgtype.UUID
	Quantity  pgtype.Numeric
}

type IncreaseInventoryRow struct {
	ProductID        pgtype.UUID
	PreviousQuantity pgtype.Numeric
	CurrentQuantity  pgtype.Numeric
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) IncreaseInventory(ctx context.Context, arg IncreaseInventoryParams) (IncreaseInventoryRow, error) {
	row := q.db.QueryRow(ctx, increaseInventory, arg.ProductID, arg.Quantity)
	var i IncreaseInventoryRow
	err := row.Scan(
		&i.ProductID,
		&i.PreviousQuantity,
		&i.CurrentQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInventory = `-- name: ListInventory :many
SELECT
    p.id AS product_id,
    p.sku,
    p.barcode,
    p.name,
    p.is_active,
    i.quantity,
    i.created_at,
    i.updated_at
FROM inventory i
INNER JOIN products p ON p.id = i.product_id
WHERE
    (
        CAST($1 AS TEXT) IS NULL
        OR p.name ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.sku ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR p.barcode ILIKE '%' || CAST($1 AS TEXT) || '%'
    )
    AND (NOT $2 OR p.is_active = TRUE)
ORDER BY p.name ASC, p.id ASC
LIMIT $4
OFFSET $3
`

type ListInventoryParams struct {
	Search     pgtype.Text
	ActiveOnly interface{}
	PageOffset int32
	PageSize   int32
}

type ListInventoryRow struct {
	ProductID pgtype.UUID
	SKU       string
	Barcode   pgtype.Text
	Name      string
	IsActive  bool
	Quantity  pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListInventory(ctx context.Context, arg ListInventoryParams) ([]ListInventoryRow, error) {
	rows, err := q.db.Query(ctx, listInventory,
		arg.Search,
		arg.ActiveOnly,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInventoryRow{}
	for rows.Next() {
		var i ListInventoryRow
		if err := rows.Scan(
			&i.ProductID,
			&i.SKU,
			&i.Barcode,
			&i.Name,
			&i.IsActive,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryMovementsByProductID = `-- name: ListInventoryMovementsByProductID :many
SELECT
    id,
    product_id,
    movement_type,
    quantity,
    previous_quantity,
    current_quantity,
    reason,
    reference_type,
    reference_id,
    created_at
FROM inventory_movements
WHERE product_id = $1
  AND (
      CAST($2 AS inventory_movement_type) IS NULL
      OR movement_type = CAST($2 AS inventory_movement_type)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
OFFSET $3
`

type ListInventoryMovementsByProductIDParams struct {
	ProductID          pgtype.UUID
	MovementTypeFilter NullInventoryMovementType
	PageOffset         int32
	PageSize           int32
}

func (q *Queries) ListInventoryMovementsByProductID(ctx context.Context, arg ListInventoryMovementsByProductIDParams) ([]InventoryMovement, error) {
	rows, err := q.db.Query(ctx, listInventoryMovementsByProductID,
		arg.ProductID,
		arg.MovementTypeFilter,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryMovement{}
	for rows.Next() {
		var i InventoryMovement
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.MovementType,
			&i.Quantity,
			&i.PreviousQuantity,
			&i.CurrentQuantity,
			&i.Reason,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
