// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE organization_invitations
SET
    status = 'ACCEPTED',
    accepted_at = NOW(),
    accepted_by_membership_id = $1
WHERE organization_id = $2
  AND id = $3
  AND status = 'PENDING'
  AND expires_at > NOW()
RETURNING
    id,
    organization_id,
    status,
    accepted_at,
    accepted_by_membership_id,
    updated_at
`

type AcceptInvitationParams struct {
	AcceptedByMembershipID pgtype.UUID
	OrganizationID         pgtype.UUID
	InvitationID           pgtype.UUID
}

type AcceptInvitationRow struct {
	ID                     pgtype.UUID
	OrganizationID         pgtype.UUID
	Status                 InvitationStatus
	AcceptedAt             pgtype.Timestamptz
	AcceptedByMembershipID pgtype.UUID
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (AcceptInvitationRow, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.AcceptedByMembershipID, arg.OrganizationID, arg.InvitationID)
	var i AcceptInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Status,
		&i.AcceptedAt,
		&i.AcceptedByMembershipID,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO organization_invitations (
    organization_id,
    email,
    email_normalized,
    secret_hash,
    expires_at,
    invited_by_membership_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    organization_id,
    email,
    email_normalized,
    status,
    secret_hash,
    expires_at,
    accepted_at,
    revoked_at,
    invited_by_membership_id,
    accepted_by_membership_id,
    created_at,
    updated_at
`

type CreateInvitationParams struct {
	OrganizationID        pgtype.UUID
	Email                 string
	EmailNormalized       string
	SecretHash            []byte
	ExpiresAt             pgtype.Timestamptz
	InvitedByMembershipID pgtype.UUID
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.EmailNormalized,
		arg.SecretHash,
		arg.ExpiresAt,
		arg.InvitedByMembershipID,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.EmailNormalized,
		&i.Status,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.InvitedByMembershipID,
		&i.AcceptedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvitationRoleBindings = `-- name: CreateInvitationRoleBindings :many
INSERT INTO invitation_role_bindings (
    organization_id,
    invitation_id,
    role_id,
    store_id
)
SELECT
    $1,
    $2,
    requested.role_id,
    requested.store_id
FROM jsonb_to_recordset(CAST($3 AS JSONB))
    AS requested(role_id UUID, store_id UUID)
ON CONFLICT DO NOTHING
RETURNING
    id,
    organization_id,
    invitation_id,
    role_id,
    store_id,
    created_at
`

type CreateInvitationRoleBindingsParams struct {
	OrganizationID pgtype.UUID
	InvitationID   pgtype.UUID
	Assignments    []byte
}

func (q *Queries) CreateInvitationRoleBindings(ctx context.Context, arg CreateInvitationRoleBindingsParams) ([]InvitationRoleBinding, error) {
	rows, err := q.db.Query(ctx, createInvitationRoleBindings, arg.OrganizationID, arg.InvitationID, arg.Assignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvitationRoleBinding{}
	for rows.Next() {
		var i InvitationRoleBinding
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvitationID,
			&i.RoleID,
			&i.StoreID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvitationForUpdate = `-- name: GetInvitationForUpdate :one
SELECT
    id,
    organization_id,
    email,
    email_normalized,
    status,
    secret_hash,
    expires_at,
    accepted_at,
    revoked_at,
    invited_by_membership_id,
    accepted_by_membership_id,
    created_at,
    updated_at
FROM organization_invitations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetInvitationForUpdate(ctx context.Context, id pgtype.UUID) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationForUpdate, id)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.EmailNormalized,
		&i.Status,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.InvitedByMembershipID,
		&i.AcceptedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvitationRoleBindings = `-- name: ListInvitationRoleBindings :many
SELECT
    b.id,
    b.organization_id,
    b.invitation_id,
    b.role_id,
    b.store_id,
    b.created_at,
    r.key AS role_key,
    r.assignment_scope,
    s.code AS store_code,
    s.name AS store_name
FROM invitation_role_bindings AS b
JOIN roles AS r
  ON r.organization_id = b.organization_id
 AND r.id = b.role_id
LEFT JOIN stores AS s
  ON s.organization_id = b.organization_id
 AND s.id = b.store_id
WHERE b.organization_id = $1
  AND b.invitation_id = $2
ORDER BY r.assignment_scope ASC, r.key ASC, s.name ASC NULLS FIRST, b.id ASC
`

type ListInvitationRoleBindingsParams struct {
	OrganizationID pgtype.UUID
	InvitationID   pgtype.UUID
}

type ListInvitationRoleBindingsRow struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	InvitationID    pgtype.UUID
	RoleID          pgtype.UUID
	StoreID         pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	RoleKey         string
	AssignmentScope RoleAssignmentScope
	StoreCode       pgtype.Text
	StoreName       pgtype.Text
}

func (q *Queries) ListInvitationRoleBindings(ctx context.Context, arg ListInvitationRoleBindingsParams) ([]ListInvitationRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, listInvitationRoleBindings, arg.OrganizationID, arg.InvitationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationRoleBindingsRow{}
	for rows.Next() {
		var i ListInvitationRoleBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.InvitationID,
			&i.RoleID,
			&i.StoreID,
			&i.CreatedAt,
			&i.RoleKey,
			&i.AssignmentScope,
			&i.StoreCode,
			&i.StoreName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE organization_invitations
SET
    status = 'REVOKED',
    revoked_at = NOW()
WHERE organization_id = $1
  AND id = $2
  AND status = 'PENDING'
RETURNING
    id,
    organization_id,
    status,
    revoked_at,
    updated_at
`

type RevokeInvitationParams struct {
	OrganizationID pgtype.UUID
	InvitationID   pgtype.UUID
}

type RevokeInvitationRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Status         InvitationStatus
	RevokedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (RevokeInvitationRow, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, arg.OrganizationID, arg.InvitationID)
	var i RevokeInvitationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Status,
		&i.RevokedAt,
		&i.UpdatedAt,
	)
	return i, err
}
