// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMemberships = `-- name: CountMemberships :one
SELECT COUNT(*)
FROM organization_memberships AS m
JOIN users AS u ON u.id = m.user_id
WHERE m.organization_id = $1
  AND (
      CAST($2 AS membership_status) IS NULL
      OR m.status = CAST($2 AS membership_status)
  )
  AND (
      CAST($3 AS TEXT) IS NULL
      OR u.display_name ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR u.email_normalized ILIKE '%' || CAST($3 AS TEXT) || '%'
  )
`

type CountMembershipsParams struct {
	OrganizationID pgtype.UUID
	Status         NullMembershipStatus
	Search         pgtype.Text
}

func (q *Queries) CountMemberships(ctx context.Context, arg CountMembershipsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMemberships, arg.OrganizationID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO organization_memberships (
    organization_id,
    user_id,
    default_store_id,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    organization_id,
    user_id,
    status,
    default_store_id,
    authorization_version,
    joined_at,
    suspended_at,
    removed_at,
    created_by_user_id,
    created_at,
    updated_at
`

type CreateMembershipParams struct {
	OrganizationID  pgtype.UUID
	UserID          pgtype.UUID
	DefaultStoreID  pgtype.UUID
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.OrganizationID,
		arg.UserID,
		arg.DefaultStoreID,
		arg.CreatedByUserID,
	)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.DefaultStoreID,
		&i.AuthorizationVersion,
		&i.JoinedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveMembership = `-- name: GetActiveMembership :one
SELECT
    m.id,
    m.organization_id,
    m.user_id,
    m.status,
    m.default_store_id,
    m.authorization_version,
    m.joined_at,
    m.suspended_at,
    m.removed_at,
    m.created_by_user_id,
    m.created_at,
    m.updated_at
FROM organization_memberships AS m
JOIN organizations AS o ON o.id = m.organization_id
JOIN users AS u ON u.id = m.user_id
WHERE m.organization_id = $1
  AND m.user_id = $2
  AND m.status = 'ACTIVE'
  AND o.status = 'ACTIVE'
  AND u.status = 'ACTIVE'
LIMIT 1
`

type GetActiveMembershipParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getActiveMembership, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.DefaultStoreID,
		&i.AuthorizationVersion,
		&i.JoinedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMembershipForUserInOrganization = `-- name: GetLatestMembershipForUserInOrganization :one
SELECT id, organization_id, user_id, status, default_store_id, authorization_version,
       joined_at, suspended_at, removed_at, created_by_user_id, created_at, updated_at
FROM organization_memberships
WHERE organization_id = $1 AND user_id = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetLatestMembershipForUserInOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) GetLatestMembershipForUserInOrganization(ctx context.Context, arg GetLatestMembershipForUserInOrganizationParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getLatestMembershipForUserInOrganization, arg.OrganizationID, arg.UserID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.DefaultStoreID,
		&i.AuthorizationVersion,
		&i.JoinedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipContextForUser = `-- name: GetMembershipContextForUser :one
SELECT
    m.id,
    m.organization_id,
    m.user_id,
    m.status,
    m.default_store_id,
    m.authorization_version,
    m.joined_at,
    m.suspended_at,
    m.removed_at,
    m.created_by_user_id,
    m.created_at,
    m.updated_at,
    o.name AS organization_name,
    o.slug AS organization_slug,
    o.status AS organization_status,
    o.authorization_version AS organization_authorization_version
FROM organization_memberships AS m
JOIN organizations AS o ON o.id = m.organization_id
WHERE m.organization_id = $1
  AND m.user_id = $2
  AND m.status <> 'REMOVED'
ORDER BY m.joined_at ASC, m.id ASC
LIMIT 1
`

type GetMembershipContextForUserParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

type GetMembershipContextForUserRow struct {
	ID                               pgtype.UUID
	OrganizationID                   pgtype.UUID
	UserID                           pgtype.UUID
	Status                           MembershipStatus
	DefaultStoreID                   pgtype.UUID
	AuthorizationVersion             int64
	JoinedAt                         pgtype.Timestamptz
	SuspendedAt                      pgtype.Timestamptz
	RemovedAt                        pgtype.Timestamptz
	CreatedByUserID                  pgtype.UUID
	CreatedAt                        pgtype.Timestamptz
	UpdatedAt                        pgtype.Timestamptz
	OrganizationName                 string
	OrganizationSlug                 string
	OrganizationStatus               OrganizationStatus
	OrganizationAuthorizationVersion int64
}

func (q *Queries) GetMembershipContextForUser(ctx context.Context, arg GetMembershipContextForUserParams) (GetMembershipContextForUserRow, error) {
	row := q.db.QueryRow(ctx, getMembershipContextForUser, arg.OrganizationID, arg.UserID)
	var i GetMembershipContextForUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.DefaultStoreID,
		&i.AuthorizationVersion,
		&i.JoinedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.OrganizationSlug,
		&i.OrganizationStatus,
		&i.OrganizationAuthorizationVersion,
	)
	return i, err
}

const getMembershipForOrganization = `-- name: GetMembershipForOrganization :one
SELECT m.id, m.organization_id, m.user_id, m.status, m.default_store_id,
       m.authorization_version, m.joined_at, m.suspended_at, m.removed_at,
       m.created_by_user_id, m.created_at, m.updated_at,
       u.email, u.display_name, u.status AS user_status, u.email_verified_at,
       s.code AS default_store_code, s.name AS default_store_name, s.status AS default_store_status
FROM organization_memberships AS m
JOIN users AS u ON u.id = m.user_id
LEFT JOIN stores AS s ON s.organization_id = m.organization_id AND s.id = m.default_store_id
WHERE m.organization_id = $1 AND m.id = $2
`

type GetMembershipForOrganizationParams struct {
	OrganizationID pgtype.UUID
	MembershipID   pgtype.UUID
}

type GetMembershipForOrganizationRow struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	UserID               pgtype.UUID
	Status               MembershipStatus
	DefaultStoreID       pgtype.UUID
	AuthorizationVersion int64
	JoinedAt             pgtype.Timestamptz
	SuspendedAt          pgtype.Timestamptz
	RemovedAt            pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Email                string
	DisplayName          string
	UserStatus           UserStatus
	EmailVerifiedAt      pgtype.Timestamptz
	DefaultStoreCode     pgtype.Text
	DefaultStoreName     pgtype.Text
	DefaultStoreStatus   NullStoreStatus
}

func (q *Queries) GetMembershipForOrganization(ctx context.Context, arg GetMembershipForOrganizationParams) (GetMembershipForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getMembershipForOrganization, arg.OrganizationID, arg.MembershipID)
	var i GetMembershipForOrganizationRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.DefaultStoreID,
		&i.AuthorizationVersion,
		&i.JoinedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
		&i.UserStatus,
		&i.EmailVerifiedAt,
		&i.DefaultStoreCode,
		&i.DefaultStoreName,
		&i.DefaultStoreStatus,
	)
	return i, err
}

const getMembershipForUpdate = `-- name: GetMembershipForUpdate :one
SELECT
    id,
    organization_id,
    user_id,
    status,
    default_store_id,
    authorization_version,
    joined_at,
    suspended_at,
    removed_at,
    created_by_user_id,
    created_at,
    updated_at
FROM organization_memberships
WHERE organization_id = $1
  AND id = $2
FOR UPDATE
`

type GetMembershipForUpdateParams struct {
	OrganizationID pgtype.UUID
	MembershipID   pgtype.UUID
}

func (q *Queries) GetMembershipForUpdate(ctx context.Context, arg GetMembershipForUpdateParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipForUpdate, arg.OrganizationID, arg.MembershipID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.DefaultStoreID,
		&i.AuthorizationVersion,
		&i.JoinedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementMembershipAuthorizationVersion = `-- name: IncrementMembershipAuthorizationVersion :one
UPDATE organization_memberships
SET authorization_version = authorization_version + 1
WHERE organization_id = $1
  AND id = $2
RETURNING
    id,
    organization_id,
    authorization_version,
    updated_at
`

type IncrementMembershipAuthorizationVersionParams struct {
	OrganizationID pgtype.UUID
	MembershipID   pgtype.UUID
}

type IncrementMembershipAuthorizationVersionRow struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	AuthorizationVersion int64
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) IncrementMembershipAuthorizationVersion(ctx context.Context, arg IncrementMembershipAuthorizationVersionParams) (IncrementMembershipAuthorizationVersionRow, error) {
	row := q.db.QueryRow(ctx, incrementMembershipAuthorizationVersion, arg.OrganizationID, arg.MembershipID)
	var i IncrementMembershipAuthorizationVersionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.AuthorizationVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemberships = `-- name: ListMemberships :many
SELECT
    m.id,
    m.organization_id,
    m.user_id,
    m.status,
    m.default_store_id,
    m.authorization_version,
    m.joined_at,
    m.suspended_at,
    m.removed_at,
    m.created_by_user_id,
    m.created_at,
    m.updated_at,
    u.email,
    u.email_normalized,
    u.display_name,
    u.status AS user_status,
    s.code AS default_store_code,
    s.name AS default_store_name
FROM organization_memberships AS m
JOIN users AS u ON u.id = m.user_id
LEFT JOIN stores AS s
  ON s.organization_id = m.organization_id
 AND s.id = m.default_store_id
WHERE m.organization_id = $1
  AND (
      CAST($2 AS membership_status) IS NULL
      OR m.status = CAST($2 AS membership_status)
  )
  AND (
      CAST($3 AS TEXT) IS NULL
      OR u.display_name ILIKE '%' || CAST($3 AS TEXT) || '%'
      OR u.email_normalized ILIKE '%' || CAST($3 AS TEXT) || '%'
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $5
OFFSET $4
`

type ListMembershipsParams struct {
	OrganizationID pgtype.UUID
	Status         NullMembershipStatus
	Search         pgtype.Text
	PageOffset     int32
	PageSize       int32
}

type ListMembershipsRow struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	UserID               pgtype.UUID
	Status               MembershipStatus
	DefaultStoreID       pgtype.UUID
	AuthorizationVersion int64
	JoinedAt             pgtype.Timestamptz
	SuspendedAt          pgtype.Timestamptz
	RemovedAt            pgtype.Timestamptz
	CreatedByUserID      pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	Email                string
	EmailNormalized      string
	DisplayName          string
	UserStatus           UserStatus
	DefaultStoreCode     pgtype.Text
	DefaultStoreName     pgtype.Text
}

func (q *Queries) ListMemberships(ctx context.Context, arg ListMembershipsParams) ([]ListMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listMemberships,
		arg.OrganizationID,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsRow{}
	for rows.Next() {
		var i ListMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Status,
			&i.DefaultStoreID,
			&i.AuthorizationVersion,
			&i.JoinedAt,
			&i.SuspendedAt,
			&i.RemovedAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.EmailNormalized,
			&i.DisplayName,
			&i.UserStatus,
			&i.DefaultStoreCode,
			&i.DefaultStoreName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE organization_memberships
SET
    status = $1,
    suspended_at = CASE
        WHEN $1::membership_status = 'SUSPENDED' THEN NOW()
        ELSE NULL
    END,
    removed_at = CASE
        WHEN $1::membership_status = 'REMOVED' THEN NOW()
        ELSE NULL
    END,
    authorization_version = authorization_version + 1
WHERE organization_id = $2
  AND id = $3
RETURNING
    id,
    organization_id,
    user_id,
    status,
    default_store_id,
    authorization_version,
    joined_at,
    suspended_at,
    removed_at,
    created_by_user_id,
    created_at,
    updated_at
`

type UpdateMembershipStatusParams struct {
	Status         MembershipStatus
	OrganizationID pgtype.UUID
	MembershipID   pgtype.UUID
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (OrganizationMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipStatus, arg.Status, arg.OrganizationID, arg.MembershipID)
	var i OrganizationMembership
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Status,
		&i.DefaultStoreID,
		&i.AuthorizationVersion,
		&i.JoinedAt,
		&i.SuspendedAt,
		&i.RemovedAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
