// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

// Lifecycle status of a fiscal document emission.
type FiscalDocumentStatus string

const (
	FiscalDocumentStatusPENDING    FiscalDocumentStatus = "PENDING"
	FiscalDocumentStatusPROCESSING FiscalDocumentStatus = "PROCESSING"
	FiscalDocumentStatusAUTHORIZED FiscalDocumentStatus = "AUTHORIZED"
	FiscalDocumentStatusREJECTED   FiscalDocumentStatus = "REJECTED"
	FiscalDocumentStatusERROR      FiscalDocumentStatus = "ERROR"
	FiscalDocumentStatusCANCELLED  FiscalDocumentStatus = "CANCELLED"
)

func (e *FiscalDocumentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FiscalDocumentStatus(s)
	case string:
		*e = FiscalDocumentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FiscalDocumentStatus: %T", src)
	}
	return nil
}

type NullFiscalDocumentStatus struct {
	FiscalDocumentStatus FiscalDocumentStatus
	Valid                bool // Valid is true if FiscalDocumentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFiscalDocumentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FiscalDocumentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FiscalDocumentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFiscalDocumentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FiscalDocumentStatus), nil
}

func (e FiscalDocumentStatus) Valid() bool {
	switch e {
	case FiscalDocumentStatusPENDING,
		FiscalDocumentStatusPROCESSING,
		FiscalDocumentStatusAUTHORIZED,
		FiscalDocumentStatusREJECTED,
		FiscalDocumentStatusERROR,
		FiscalDocumentStatusCANCELLED:
		return true
	}
	return false
}

// Fiscal authority environment used for document emission.
type FiscalEnvironment string

const (
	FiscalEnvironmentHOMOLOGATION FiscalEnvironment = "HOMOLOGATION"
	FiscalEnvironmentPRODUCTION   FiscalEnvironment = "PRODUCTION"
)

func (e *FiscalEnvironment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FiscalEnvironment(s)
	case string:
		*e = FiscalEnvironment(s)
	default:
		return fmt.Errorf("unsupported scan type for FiscalEnvironment: %T", src)
	}
	return nil
}

type NullFiscalEnvironment struct {
	FiscalEnvironment FiscalEnvironment
	Valid             bool // Valid is true if FiscalEnvironment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFiscalEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.FiscalEnvironment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FiscalEnvironment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFiscalEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FiscalEnvironment), nil
}

func (e FiscalEnvironment) Valid() bool {
	switch e {
	case FiscalEnvironmentHOMOLOGATION,
		FiscalEnvironmentPRODUCTION:
		return true
	}
	return false
}

type InventoryMovementType string

const (
	InventoryMovementTypePURCHASE         InventoryMovementType = "PURCHASE"
	InventoryMovementTypeSALE             InventoryMovementType = "SALE"
	InventoryMovementTypeSALECANCELLATION InventoryMovementType = "SALE_CANCELLATION"
	InventoryMovementTypeADJUSTMENTIN     InventoryMovementType = "ADJUSTMENT_IN"
	InventoryMovementTypeADJUSTMENTOUT    InventoryMovementType = "ADJUSTMENT_OUT"
)

func (e *InventoryMovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryMovementType(s)
	case string:
		*e = InventoryMovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryMovementType: %T", src)
	}
	return nil
}

type NullInventoryMovementType struct {
	InventoryMovementType InventoryMovementType
	Valid                 bool // Valid is true if InventoryMovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryMovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryMovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryMovementType), nil
}

func (e InventoryMovementType) Valid() bool {
	switch e {
	case InventoryMovementTypePURCHASE,
		InventoryMovementTypeSALE,
		InventoryMovementTypeSALECANCELLATION,
		InventoryMovementTypeADJUSTMENTIN,
		InventoryMovementTypeADJUSTMENTOUT:
		return true
	}
	return false
}

type PaymentMethodKind string

const (
	PaymentMethodKindCASH        PaymentMethodKind = "CASH"
	PaymentMethodKindPIX         PaymentMethodKind = "PIX"
	PaymentMethodKindDEBITCARD   PaymentMethodKind = "DEBIT_CARD"
	PaymentMethodKindCREDITCARD  PaymentMethodKind = "CREDIT_CARD"
	PaymentMethodKindVOUCHER     PaymentMethodKind = "VOUCHER"
	PaymentMethodKindSTORECREDIT PaymentMethodKind = "STORE_CREDIT"
	PaymentMethodKindOTHER       PaymentMethodKind = "OTHER"
)

func (e *PaymentMethodKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethodKind(s)
	case string:
		*e = PaymentMethodKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethodKind: %T", src)
	}
	return nil
}

type NullPaymentMethodKind struct {
	PaymentMethodKind PaymentMethodKind
	Valid             bool // Valid is true if PaymentMethodKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethodKind) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethodKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethodKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethodKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethodKind), nil
}

func (e PaymentMethodKind) Valid() bool {
	switch e {
	case PaymentMethodKindCASH,
		PaymentMethodKindPIX,
		PaymentMethodKindDEBITCARD,
		PaymentMethodKindCREDITCARD,
		PaymentMethodKindVOUCHER,
		PaymentMethodKindSTORECREDIT,
		PaymentMethodKindOTHER:
		return true
	}
	return false
}

// Lifecycle status of a payment transaction.
type PaymentStatus string

const (
	PaymentStatusPENDING   PaymentStatus = "PENDING"
	PaymentStatusAPPROVED  PaymentStatus = "APPROVED"
	PaymentStatusDECLINED  PaymentStatus = "DECLINED"
	PaymentStatusCANCELLED PaymentStatus = "CANCELLED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusPENDING,
		PaymentStatusAPPROVED,
		PaymentStatusDECLINED,
		PaymentStatusCANCELLED:
		return true
	}
	return false
}

// Lifecycle status of a POS sale.
type SaleStatus string

const (
	SaleStatusOPEN      SaleStatus = "OPEN"
	SaleStatusCOMPLETED SaleStatus = "COMPLETED"
	SaleStatusCANCELLED SaleStatus = "CANCELLED"
)

func (e *SaleStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SaleStatus(s)
	case string:
		*e = SaleStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SaleStatus: %T", src)
	}
	return nil
}

type NullSaleStatus struct {
	SaleStatus SaleStatus
	Valid      bool // Valid is true if SaleStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSaleStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SaleStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SaleStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSaleStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SaleStatus), nil
}

func (e SaleStatus) Valid() bool {
	switch e {
	case SaleStatusOPEN,
		SaleStatusCOMPLETED,
		SaleStatusCANCELLED:
		return true
	}
	return false
}

// Stores fiscal documents issued for completed POS sales.
type FiscalDocument struct {
	ID pgtype.UUID
	// Sale associated with the fiscal document.
	SaleID      pgtype.UUID
	Status      FiscalDocumentStatus
	Environment FiscalEnvironment
	// Fiscal document model. Model 65 represents NFC-e.
	DocumentModel int16
	Series        pgtype.Int4
	Number        pgtype.Int8
	// Fiscal document access key returned after authorization.
	AccessKey pgtype.Text
	// Authorization protocol returned by the fiscal authority or provider.
	Protocol pgtype.Text
	Provider pgtype.Text
	// Transaction identifier assigned by the fiscal integration provider.
	ExternalReference pgtype.Text
	// Fiscal document XML generated or returned during emission.
	XML          pgtype.Text
	ErrorCode    pgtype.Text
	ErrorMessage pgtype.Text
	IssuedAt     pgtype.Timestamptz
	CancelledAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type FiscalDocumentCallback struct {
	ID               pgtype.UUID
	FiscalDocumentID pgtype.UUID
	Provider         string
	CallbackKey      string
	Payload          string
	ReceivedAt       pgtype.Timestamptz
	ProcessedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Inventory struct {
	ProductID pgtype.UUID
	Quantity  pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type InventoryMovement struct {
	ID               pgtype.UUID
	ProductID        pgtype.UUID
	MovementType     InventoryMovementType
	Quantity         pgtype.Numeric
	PreviousQuantity pgtype.Numeric
	CurrentQuantity  pgtype.Numeric
	Reason           pgtype.Text
	ReferenceType    string
	ReferenceID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type MvReceiptPayment struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	PaymentMethodName string
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type PaymentMethod struct {
	ID                        pgtype.UUID
	Code                      string
	Name                      string
	Kind                      PaymentMethodKind
	Provider                  pgtype.Text
	AllowsChange              bool
	RequiresExternalReference bool
	AllowsInstallments        bool
	MaxInstallments           int16
	FeePercentage             pgtype.Numeric
	SettlementDays            int32
	IsActive                  bool
	SortOrder                 int32
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

// Stores products available for inventory control and POS sales.
type Product struct {
	// Internal UUIDv7 identifier.
	ID pgtype.UUID
	// Unique internal stock keeping unit.
	SKU string
	// Optional unique barcode used by barcode scanners.
	Barcode pgtype.Text
	// Product name displayed in administrative and POS interfaces.
	Name string
	// Current product sale price. Historical prices are preserved in sale_items.
	Price pgtype.Numeric
	// Optional product acquisition cost used for margin calculations.
	Cost pgtype.Numeric
	// Controls whether the product can be used in new sales.
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// Stores product snapshots and monetary totals for each sale item.
type SaleItem struct {
	ID        pgtype.UUID
	SaleID    pgtype.UUID
	ProductID pgtype.UUID
	// Product name snapshot preserved at the moment of sale.
	ProductName string
	// Product SKU snapshot preserved at the moment of sale.
	ProductSKU string
	// Unit price snapshot used at the moment of sale.
	UnitPrice pgtype.Numeric
	// Quantity sold with support for up to three decimal places.
	Quantity pgtype.Numeric
	Discount pgtype.Numeric
	// Final item total rounded to two decimal places after discount.
	Total     pgtype.Numeric
	CreatedAt pgtype.Timestamptz
}
