// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO
    organizations (
        name,
        slug,
        timezone,
        locale,
        currency,
        created_by_user_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    ) RETURNING id,
    name,
    slug,
    status,
    timezone,
    locale,
    currency,
    authorization_version,
    created_by_user_id,
    archived_at,
    created_at,
    updated_at
`

type CreateOrganizationParams struct {
	Name            string
	Slug            string
	Timezone        string
	Locale          string
	Currency        string
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.Timezone,
		arg.Locale,
		arg.Currency,
		arg.CreatedByUserID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Timezone,
		&i.Locale,
		&i.Currency,
		&i.AuthorizationVersion,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationAuthorizationVersion = `-- name: GetOrganizationAuthorizationVersion :one
SELECT
    id AS organization_id,
    status,
    authorization_version
FROM organizations
WHERE
    id = $1
`

type GetOrganizationAuthorizationVersionRow struct {
	OrganizationID       pgtype.UUID
	Status               OrganizationStatus
	AuthorizationVersion int64
}

func (q *Queries) GetOrganizationAuthorizationVersion(ctx context.Context, organizationID pgtype.UUID) (GetOrganizationAuthorizationVersionRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationAuthorizationVersion, organizationID)
	var i GetOrganizationAuthorizationVersionRow
	err := row.Scan(&i.OrganizationID, &i.Status, &i.AuthorizationVersion)
	return i, err
}

const incrementOrganizationAuthorizationVersion = `-- name: IncrementOrganizationAuthorizationVersion :one
UPDATE organizations
SET
    authorization_version = authorization_version + 1
WHERE
    id = $1 RETURNING id AS organization_id,
    authorization_version,
    updated_at
`

type IncrementOrganizationAuthorizationVersionRow struct {
	OrganizationID       pgtype.UUID
	AuthorizationVersion int64
	UpdatedAt            pgtype.Timestamptz
}

func (q *Queries) IncrementOrganizationAuthorizationVersion(ctx context.Context, organizationID pgtype.UUID) (IncrementOrganizationAuthorizationVersionRow, error) {
	row := q.db.QueryRow(ctx, incrementOrganizationAuthorizationVersion, organizationID)
	var i IncrementOrganizationAuthorizationVersionRow
	err := row.Scan(&i.OrganizationID, &i.AuthorizationVersion, &i.UpdatedAt)
	return i, err
}

const lockOrganizationForOwnerChange = `-- name: LockOrganizationForOwnerChange :one
SELECT
    id AS organization_id,
    status,
    authorization_version
FROM organizations
WHERE
    id = $1 FOR
UPDATE
`

type LockOrganizationForOwnerChangeRow struct {
	OrganizationID       pgtype.UUID
	Status               OrganizationStatus
	AuthorizationVersion int64
}

func (q *Queries) LockOrganizationForOwnerChange(ctx context.Context, organizationID pgtype.UUID) (LockOrganizationForOwnerChangeRow, error) {
	row := q.db.QueryRow(ctx, lockOrganizationForOwnerChange, organizationID)
	var i LockOrganizationForOwnerChangeRow
	err := row.Scan(&i.OrganizationID, &i.Status, &i.AuthorizationVersion)
	return i, err
}
