// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePayment = `-- name: ApprovePayment :one
UPDATE payments
SET
    status = 'APPROVED',
    paid_at = NOW(),
    received_amount = COALESCE($1, received_amount),
    change_amount = COALESCE($2, change_amount)
WHERE id = $3
  AND status = 'PENDING'
RETURNING
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
`

type ApprovePaymentParams struct {
	ReceivedAmount pgtype.Numeric
	ChangeAmount   pgtype.Numeric
	ID             pgtype.UUID
}

type ApprovePaymentRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) ApprovePayment(ctx context.Context, arg ApprovePaymentParams) (ApprovePaymentRow, error) {
	row := q.db.QueryRow(ctx, approvePayment, arg.ReceivedAmount, arg.ChangeAmount, arg.ID)
	var i ApprovePaymentRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const cancelPayment = `-- name: CancelPayment :one
UPDATE payments
SET
    status = 'CANCELLED',
    cancelled_at = NOW()
WHERE id = $1
  AND status IN ('PENDING', 'APPROVED', 'DECLINED')
RETURNING
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
`

type CancelPaymentRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) CancelPayment(ctx context.Context, id pgtype.UUID) (CancelPaymentRow, error) {
	row := q.db.QueryRow(ctx, cancelPayment, id)
	var i CancelPaymentRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
WITH inserted AS (
    INSERT INTO payments (
        sale_id,
        payment_method_id,
        amount,
        received_amount,
        change_amount,
        installments,
        external_reference,
        idempotency_key
    )
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
    ON CONFLICT (idempotency_key) DO NOTHING
    RETURNING
        id,
        sale_id,
        payment_method_id,
        status,
        amount,
        received_amount,
        change_amount,
        installments,
        external_reference,
        paid_at,
        cancelled_at,
        created_at,
        updated_at,
        idempotency_key
)
SELECT
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM inserted
UNION ALL
SELECT
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM payments
WHERE idempotency_key = $8
LIMIT 1
`

type CreatePaymentParams struct {
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	IdempotencyKey    string
}

type CreatePaymentRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.SaleID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.ReceivedAmount,
		arg.ChangeAmount,
		arg.Installments,
		arg.ExternalReference,
		arg.IdempotencyKey,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const declinePayment = `-- name: DeclinePayment :one
UPDATE payments
SET
    status = 'DECLINED'
WHERE id = $1
  AND status = 'PENDING'
RETURNING
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
`

type DeclinePaymentRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) DeclinePayment(ctx context.Context, id pgtype.UUID) (DeclinePaymentRow, error) {
	row := q.db.QueryRow(ctx, declinePayment, id)
	var i DeclinePaymentRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByExternalReference = `-- name: GetPaymentByExternalReference :one
SELECT
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM payments
WHERE payment_method_id = $1
  AND external_reference = $2
LIMIT 1
`

type GetPaymentByExternalReferenceParams struct {
	PaymentMethodID   pgtype.UUID
	ExternalReference pgtype.Text
}

type GetPaymentByExternalReferenceRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) GetPaymentByExternalReference(ctx context.Context, arg GetPaymentByExternalReferenceParams) (GetPaymentByExternalReferenceRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByExternalReference, arg.PaymentMethodID, arg.ExternalReference)
	var i GetPaymentByExternalReferenceRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM payments
WHERE id = $1
LIMIT 1
`

type GetPaymentByIDRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (GetPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM payments
WHERE idempotency_key = $1
LIMIT 1
`

type GetPaymentByIdempotencyKeyRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetPaymentByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i GetPaymentByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const listPaymentsBySaleID = `-- name: ListPaymentsBySaleID :many
SELECT
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM payments
WHERE sale_id = $1
ORDER BY created_at, id
`

type ListPaymentsBySaleIDRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) ListPaymentsBySaleID(ctx context.Context, saleID pgtype.UUID) ([]ListPaymentsBySaleIDRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsBySaleID, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsBySaleIDRow{}
	for rows.Next() {
		var i ListPaymentsBySaleIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.PaymentMethodID,
			&i.Status,
			&i.Amount,
			&i.ReceivedAmount,
			&i.ChangeAmount,
			&i.Installments,
			&i.ExternalReference,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentByID = `-- name: LockPaymentByID :one
SELECT
    id,
    sale_id,
    payment_method_id,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM payments
WHERE id = $1
FOR UPDATE
`

type LockPaymentByIDRow struct {
	ID                pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	IdempotencyKey    string
}

func (q *Queries) LockPaymentByID(ctx context.Context, id pgtype.UUID) (LockPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, lockPaymentByID, id)
	var i LockPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}
