// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvePaymentForStore = `-- name: ApprovePaymentForStore :one
UPDATE payments AS payment
SET
    status = 'APPROVED',
    paid_at = NOW(),
    received_amount = COALESCE($1, payment.received_amount),
    change_amount = COALESCE($2, payment.change_amount)
WHERE payment.organization_id = $3
  AND payment.store_id = $4
  AND payment.id = $5
  AND payment.status = 'PENDING'
RETURNING
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
`

type ApprovePaymentForStoreParams struct {
	ReceivedAmount pgtype.Numeric
	ChangeAmount   pgtype.Numeric
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) ApprovePaymentForStore(ctx context.Context, arg ApprovePaymentForStoreParams) (Payment, error) {
	row := q.db.QueryRow(ctx, approvePaymentForStore,
		arg.ReceivedAmount,
		arg.ChangeAmount,
		arg.OrganizationID,
		arg.StoreID,
		arg.ID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelPaymentForStore = `-- name: CancelPaymentForStore :one
UPDATE payments AS payment
SET
    status = 'CANCELLED',
    cancelled_at = NOW()
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.id = $3
  AND payment.status IN ('PENDING', 'APPROVED')
RETURNING
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
`

type CancelPaymentForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) CancelPaymentForStore(ctx context.Context, arg CancelPaymentForStoreParams) (Payment, error) {
	row := q.db.QueryRow(ctx, cancelPaymentForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countPaymentsBySaleIDForStore = `-- name: CountPaymentsBySaleIDForStore :one
SELECT COUNT(*)
FROM payments AS payment
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.sale_id = $3
`

type CountPaymentsBySaleIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	SaleID         pgtype.UUID
}

func (q *Queries) CountPaymentsBySaleIDForStore(ctx context.Context, arg CountPaymentsBySaleIDForStoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentsBySaleIDForStore, arg.OrganizationID, arg.StoreID, arg.SaleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentForStore = `-- name: CreatePaymentForStore :one
WITH existing AS MATERIALIZED (
    SELECT
        payment.id,
        payment.organization_id,
        payment.store_id,
        payment.sale_id,
        payment.payment_method_id,
        payment.idempotency_key,
        payment.status,
        payment.amount,
        payment.received_amount,
        payment.change_amount,
        payment.installments,
        payment.external_reference,
        payment.paid_at,
        payment.cancelled_at,
        payment.created_at,
        payment.updated_at
    FROM payments AS payment
    WHERE payment.organization_id = $1
      AND payment.store_id = $2
      AND payment.idempotency_key = $3
), inserted AS (
    INSERT INTO payments (
        organization_id,
        store_id,
        sale_id,
        payment_method_id,
        idempotency_key,
        amount,
        received_amount,
        change_amount,
        installments,
        external_reference
    )
    SELECT
        $1,
        $2,
        $4,
        $5,
        $3,
        $6,
        $7,
        $8,
        $9,
        $10
    FROM store_payment_methods AS binding
    INNER JOIN payment_methods AS method
        ON method.organization_id = binding.organization_id
       AND method.id = binding.payment_method_id
    WHERE binding.organization_id = $1
      AND binding.store_id = $2
      AND binding.payment_method_id = $5
      AND binding.is_active = TRUE
      AND method.is_active = TRUE
      AND NOT EXISTS (SELECT 1 FROM existing)
    ON CONFLICT (organization_id, store_id, idempotency_key) DO UPDATE
    SET idempotency_key = EXCLUDED.idempotency_key
    RETURNING
        id,
        organization_id,
        store_id,
        sale_id,
        payment_method_id,
        idempotency_key,
        status,
        amount,
        received_amount,
        change_amount,
        installments,
        external_reference,
        paid_at,
        cancelled_at,
        created_at,
        updated_at
)
SELECT id, organization_id, store_id, sale_id, payment_method_id, idempotency_key, status, amount, received_amount, change_amount, installments, external_reference, paid_at, cancelled_at, created_at, updated_at FROM inserted
UNION ALL
SELECT id, organization_id, store_id, sale_id, payment_method_id, idempotency_key, status, amount, received_amount, change_amount, installments, external_reference, paid_at, cancelled_at, created_at, updated_at FROM existing
UNION ALL
SELECT
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
FROM payments AS payment
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.idempotency_key = $3
  AND NOT EXISTS (SELECT 1 FROM inserted)
  AND NOT EXISTS (SELECT 1 FROM existing)
LIMIT 1
`

type CreatePaymentForStoreParams struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	IdempotencyKey    string
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
}

type CreatePaymentForStoreRow struct {
	ID                pgtype.UUID
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	SaleID            pgtype.UUID
	PaymentMethodID   pgtype.UUID
	IdempotencyKey    string
	Status            PaymentStatus
	Amount            pgtype.Numeric
	ReceivedAmount    pgtype.Numeric
	ChangeAmount      pgtype.Numeric
	Installments      int16
	ExternalReference pgtype.Text
	PaidAt            pgtype.Timestamptz
	CancelledAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) CreatePaymentForStore(ctx context.Context, arg CreatePaymentForStoreParams) (CreatePaymentForStoreRow, error) {
	row := q.db.QueryRow(ctx, createPaymentForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.IdempotencyKey,
		arg.SaleID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.ReceivedAmount,
		arg.ChangeAmount,
		arg.Installments,
		arg.ExternalReference,
	)
	var i CreatePaymentForStoreRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const declinePaymentForStore = `-- name: DeclinePaymentForStore :one
UPDATE payments AS payment
SET status = 'DECLINED'
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.id = $3
  AND payment.status = 'PENDING'
RETURNING
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
`

type DeclinePaymentForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) DeclinePaymentForStore(ctx context.Context, arg DeclinePaymentForStoreParams) (Payment, error) {
	row := q.db.QueryRow(ctx, declinePaymentForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByExternalReferenceForStore = `-- name: GetPaymentByExternalReferenceForStore :one
SELECT
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
FROM payments AS payment
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.payment_method_id = $3
  AND payment.external_reference = $4
LIMIT 1
`

type GetPaymentByExternalReferenceForStoreParams struct {
	OrganizationID    pgtype.UUID
	StoreID           pgtype.UUID
	PaymentMethodID   pgtype.UUID
	ExternalReference pgtype.Text
}

func (q *Queries) GetPaymentByExternalReferenceForStore(ctx context.Context, arg GetPaymentByExternalReferenceForStoreParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByExternalReferenceForStore,
		arg.OrganizationID,
		arg.StoreID,
		arg.PaymentMethodID,
		arg.ExternalReference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIDForStore = `-- name: GetPaymentByIDForStore :one
SELECT
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
FROM payments AS payment
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.id = $3
LIMIT 1
`

type GetPaymentByIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) GetPaymentByIDForStore(ctx context.Context, arg GetPaymentByIDForStoreParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIDForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKeyForStore = `-- name: GetPaymentByIdempotencyKeyForStore :one
SELECT
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
FROM payments AS payment
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.idempotency_key = $3
LIMIT 1
`

type GetPaymentByIdempotencyKeyForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	IdempotencyKey string
}

func (q *Queries) GetPaymentByIdempotencyKeyForStore(ctx context.Context, arg GetPaymentByIdempotencyKeyForStoreParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKeyForStore, arg.OrganizationID, arg.StoreID, arg.IdempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsBySaleIDForStore = `-- name: ListPaymentsBySaleIDForStore :many
SELECT
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
FROM payments AS payment
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.sale_id = $3
ORDER BY payment.created_at, payment.id
`

type ListPaymentsBySaleIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	SaleID         pgtype.UUID
}

func (q *Queries) ListPaymentsBySaleIDForStore(ctx context.Context, arg ListPaymentsBySaleIDForStoreParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsBySaleIDForStore, arg.OrganizationID, arg.StoreID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.StoreID,
			&i.SaleID,
			&i.PaymentMethodID,
			&i.IdempotencyKey,
			&i.Status,
			&i.Amount,
			&i.ReceivedAmount,
			&i.ChangeAmount,
			&i.Installments,
			&i.ExternalReference,
			&i.PaidAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentByIDForStore = `-- name: LockPaymentByIDForStore :one
SELECT
    payment.id,
    payment.organization_id,
    payment.store_id,
    payment.sale_id,
    payment.payment_method_id,
    payment.idempotency_key,
    payment.status,
    payment.amount,
    payment.received_amount,
    payment.change_amount,
    payment.installments,
    payment.external_reference,
    payment.paid_at,
    payment.cancelled_at,
    payment.created_at,
    payment.updated_at
FROM payments AS payment
WHERE payment.organization_id = $1
  AND payment.store_id = $2
  AND payment.id = $3
FOR UPDATE
`

type LockPaymentByIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
}

func (q *Queries) LockPaymentByIDForStore(ctx context.Context, arg LockPaymentByIDForStoreParams) (Payment, error) {
	row := q.db.QueryRow(ctx, lockPaymentByIDForStore, arg.OrganizationID, arg.StoreID, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StoreID,
		&i.SaleID,
		&i.PaymentMethodID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.ChangeAmount,
		&i.Installments,
		&i.ExternalReference,
		&i.PaidAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
