// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProductForOrganization = `-- name: ActivateProductForOrganization :one
UPDATE products
SET
    is_active = TRUE,
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
RETURNING
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

type ActivateProductForOrganizationParams struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type ActivateProductForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ActivateProductForOrganization(ctx context.Context, arg ActivateProductForOrganizationParams) (ActivateProductForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, activateProductForOrganization, arg.OrganizationID, arg.ID)
	var i ActivateProductForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countProductsForOrganization = `-- name: CountProductsForOrganization :one
SELECT COUNT(*)
FROM products
WHERE organization_id = $1
  AND (
      CAST($2 AS TEXT) IS NULL
      OR name ILIKE '%' || CAST($2 AS TEXT) || '%'
      OR sku ILIKE '%' || CAST($2 AS TEXT) || '%'
      OR barcode ILIKE '%' || CAST($2 AS TEXT) || '%'
  )
  AND (
      CAST($3 AS UUID) IS NULL
      OR category_id = CAST($3 AS UUID)
  )
  AND (NOT CAST($4 AS BOOLEAN) OR is_active = TRUE)
`

type CountProductsForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Search         pgtype.Text
	CategoryID     pgtype.UUID
	ActiveOnly     bool
}

func (q *Queries) CountProductsForOrganization(ctx context.Context, arg CountProductsForOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsForOrganization,
		arg.OrganizationID,
		arg.Search,
		arg.CategoryID,
		arg.ActiveOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProductForOrganization = `-- name: CreateProductForOrganization :one
INSERT INTO products (
    organization_id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

type CreateProductForOrganizationParams struct {
	OrganizationID pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
}

type CreateProductForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateProductForOrganization(ctx context.Context, arg CreateProductForOrganizationParams) (CreateProductForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, createProductForOrganization,
		arg.OrganizationID,
		arg.SKU,
		arg.Barcode,
		arg.Name,
		arg.CategoryID,
		arg.Price,
		arg.Cost,
		arg.IsActive,
	)
	var i CreateProductForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProductForOrganization = `-- name: DeactivateProductForOrganization :one
UPDATE products
SET
    is_active = FALSE,
    updated_at = NOW()
WHERE organization_id = $1
  AND id = $2
RETURNING
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

type DeactivateProductForOrganizationParams struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type DeactivateProductForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) DeactivateProductForOrganization(ctx context.Context, arg DeactivateProductForOrganizationParams) (DeactivateProductForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, deactivateProductForOrganization, arg.OrganizationID, arg.ID)
	var i DeactivateProductForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByBarcodeForOrganization = `-- name: GetProductByBarcodeForOrganization :one
SELECT
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE organization_id = $1
  AND barcode = $2
LIMIT 1
`

type GetProductByBarcodeForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Barcode        pgtype.Text
}

type GetProductByBarcodeForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetProductByBarcodeForOrganization(ctx context.Context, arg GetProductByBarcodeForOrganizationParams) (GetProductByBarcodeForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getProductByBarcodeForOrganization, arg.OrganizationID, arg.Barcode)
	var i GetProductByBarcodeForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByIDForOrganization = `-- name: GetProductByIDForOrganization :one
SELECT
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE organization_id = $1
  AND id = $2
LIMIT 1
`

type GetProductByIDForOrganizationParams struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type GetProductByIDForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetProductByIDForOrganization(ctx context.Context, arg GetProductByIDForOrganizationParams) (GetProductByIDForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getProductByIDForOrganization, arg.OrganizationID, arg.ID)
	var i GetProductByIDForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByIDForStore = `-- name: GetProductByIDForStore :one
SELECT
    p.organization_id,
    s.id AS store_id,
    p.id,
    p.sku,
    p.barcode,
    p.name,
    p.category_id,
    p.price,
    p.cost,
    p.is_active,
    p.created_at,
    p.updated_at
FROM products p
INNER JOIN stores s
        ON s.organization_id = p.organization_id
       AND s.id = $1
WHERE p.organization_id = $2
  AND p.id = $3
LIMIT 1
`

type GetProductByIDForStoreParams struct {
	StoreID        pgtype.UUID
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type GetProductByIDForStoreRow struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetProductByIDForStore(ctx context.Context, arg GetProductByIDForStoreParams) (GetProductByIDForStoreRow, error) {
	row := q.db.QueryRow(ctx, getProductByIDForStore, arg.StoreID, arg.OrganizationID, arg.ID)
	var i GetProductByIDForStoreRow
	err := row.Scan(
		&i.OrganizationID,
		&i.StoreID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySKUForOrganization = `-- name: GetProductBySKUForOrganization :one
SELECT
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE organization_id = $1
  AND sku = $2
LIMIT 1
`

type GetProductBySKUForOrganizationParams struct {
	OrganizationID pgtype.UUID
	SKU            string
}

type GetProductBySKUForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetProductBySKUForOrganization(ctx context.Context, arg GetProductBySKUForOrganizationParams) (GetProductBySKUForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, getProductBySKUForOrganization, arg.OrganizationID, arg.SKU)
	var i GetProductBySKUForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductsForOrganization = `-- name: ListProductsForOrganization :many
SELECT
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE organization_id = $1
  AND (
      CAST($2 AS TEXT) IS NULL
      OR name ILIKE '%' || CAST($2 AS TEXT) || '%'
      OR sku ILIKE '%' || CAST($2 AS TEXT) || '%'
      OR barcode ILIKE '%' || CAST($2 AS TEXT) || '%'
  )
  AND (
      CAST($3 AS UUID) IS NULL
      OR category_id = CAST($3 AS UUID)
  )
  AND (NOT CAST($4 AS BOOLEAN) OR is_active = TRUE)
ORDER BY name ASC, id ASC
LIMIT $6
OFFSET $5
`

type ListProductsForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Search         pgtype.Text
	CategoryID     pgtype.UUID
	ActiveOnly     bool
	PageOffset     int32
	PageSize       int32
}

type ListProductsForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListProductsForOrganization(ctx context.Context, arg ListProductsForOrganizationParams) ([]ListProductsForOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listProductsForOrganization,
		arg.OrganizationID,
		arg.Search,
		arg.CategoryID,
		arg.ActiveOnly,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsForOrganizationRow{}
	for rows.Next() {
		var i ListProductsForOrganizationRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.ID,
			&i.SKU,
			&i.Barcode,
			&i.Name,
			&i.CategoryID,
			&i.Price,
			&i.Cost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductForOrganization = `-- name: UpdateProductForOrganization :one
UPDATE products
SET
    sku = $1,
    barcode = $2,
    name = $3,
    category_id = $4,
    price = $5,
    cost = $6,
    updated_at = NOW()
WHERE organization_id = $7
  AND id = $8
RETURNING
    organization_id,
    id,
    sku,
    barcode,
    name,
    category_id,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

type UpdateProductForOrganizationParams struct {
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
}

type UpdateProductForOrganizationRow struct {
	OrganizationID pgtype.UUID
	ID             pgtype.UUID
	SKU            string
	Barcode        pgtype.Text
	Name           string
	CategoryID     pgtype.UUID
	Price          pgtype.Numeric
	Cost           pgtype.Numeric
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateProductForOrganization(ctx context.Context, arg UpdateProductForOrganizationParams) (UpdateProductForOrganizationRow, error) {
	row := q.db.QueryRow(ctx, updateProductForOrganization,
		arg.SKU,
		arg.Barcode,
		arg.Name,
		arg.CategoryID,
		arg.Price,
		arg.Cost,
		arg.OrganizationID,
		arg.ID,
	)
	var i UpdateProductForOrganizationRow
	err := row.Scan(
		&i.OrganizationID,
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.CategoryID,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
