// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateProduct = `-- name: ActivateProduct :one
UPDATE products
SET
    is_active = TRUE,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

func (q *Queries) ActivateProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, activateProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*)
FROM products
WHERE
    (
        CAST($1 AS TEXT) IS NULL
        OR name ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR sku ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR barcode ILIKE '%' || CAST($1 AS TEXT) || '%'
    )
    AND (NOT $2 OR is_active = TRUE)
`

type CountProductsParams struct {
	Search     pgtype.Text
	ActiveOnly interface{}
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Search, arg.ActiveOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    sku,
    barcode,
    name,
    price,
    cost,
    is_active
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

type CreateProductParams struct {
	SKU      string
	Barcode  pgtype.Text
	Name     string
	Price    pgtype.Numeric
	Cost     pgtype.Numeric
	IsActive bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.SKU,
		arg.Barcode,
		arg.Name,
		arg.Price,
		arg.Cost,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateProduct = `-- name: DeactivateProduct :one
UPDATE products
SET
    is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

func (q *Queries) DeactivateProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deactivateProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE barcode = $1
LIMIT 1
`

func (q *Queries) GetProductByBarcode(ctx context.Context, barcode pgtype.Text) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, barcode)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE sku = $1
LIMIT 1
`

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, sku)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
FROM products
WHERE
    (
        CAST($1 AS TEXT) IS NULL
        OR name ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR sku ILIKE '%' || CAST($1 AS TEXT) || '%'
        OR barcode ILIKE '%' || CAST($1 AS TEXT) || '%'
    )
    AND (NOT $2 OR is_active = TRUE)
ORDER BY name ASC, id ASC
LIMIT $4
OFFSET $3
`

type ListProductsParams struct {
	Search     pgtype.Text
	ActiveOnly interface{}
	PageOffset int32
	PageSize   int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Search,
		arg.ActiveOnly,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.SKU,
			&i.Barcode,
			&i.Name,
			&i.Price,
			&i.Cost,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    sku = $1,
    barcode = $2,
    name = $3,
    price = $4,
    cost = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING
    id,
    sku,
    barcode,
    name,
    price,
    cost,
    is_active,
    created_at,
    updated_at
`

type UpdateProductParams struct {
	SKU     string
	Barcode pgtype.Text
	Name    string
	Price   pgtype.Numeric
	Cost    pgtype.Numeric
	ID      pgtype.UUID
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.SKU,
		arg.Barcode,
		arg.Name,
		arg.Price,
		arg.Cost,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.SKU,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Cost,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
