// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReceiptPaymentsBySaleIDForStore = `-- name: CountReceiptPaymentsBySaleIDForStore :one
SELECT COUNT(*)
FROM receipt_payments AS receipt
WHERE receipt.organization_id = $1
  AND receipt.store_id = $2
  AND receipt.sale_id = $3
`

type CountReceiptPaymentsBySaleIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	SaleID         pgtype.UUID
}

func (q *Queries) CountReceiptPaymentsBySaleIDForStore(ctx context.Context, arg CountReceiptPaymentsBySaleIDForStoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReceiptPaymentsBySaleIDForStore, arg.OrganizationID, arg.StoreID, arg.SaleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listReceiptPaymentsBySaleIDForStore = `-- name: ListReceiptPaymentsBySaleIDForStore :many
SELECT
    receipt.organization_id,
    receipt.store_id,
    receipt.id,
    receipt.sale_id,
    receipt.payment_method_id,
    receipt.payment_method_name,
    receipt.status,
    receipt.amount,
    receipt.received_amount,
    receipt.change_amount,
    receipt.installments,
    receipt.external_reference,
    receipt.paid_at,
    receipt.created_at,
    receipt.updated_at
FROM receipt_payments AS receipt
WHERE receipt.organization_id = $1
  AND receipt.store_id = $2
  AND receipt.sale_id = $3
ORDER BY receipt.created_at, receipt.id
`

type ListReceiptPaymentsBySaleIDForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
	SaleID         pgtype.UUID
}

func (q *Queries) ListReceiptPaymentsBySaleIDForStore(ctx context.Context, arg ListReceiptPaymentsBySaleIDForStoreParams) ([]ReceiptPayment, error) {
	rows, err := q.db.Query(ctx, listReceiptPaymentsBySaleIDForStore, arg.OrganizationID, arg.StoreID, arg.SaleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReceiptPayment{}
	for rows.Next() {
		var i ReceiptPayment
		if err := rows.Scan(
			&i.OrganizationID,
			&i.StoreID,
			&i.ID,
			&i.SaleID,
			&i.PaymentMethodID,
			&i.PaymentMethodName,
			&i.Status,
			&i.Amount,
			&i.ReceivedAmount,
			&i.ChangeAmount,
			&i.Installments,
			&i.ExternalReference,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
