// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipt.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listReceiptPaymentsBySaleID = `-- name: ListReceiptPaymentsBySaleID :many
SELECT
    id,
    sale_id,
    payment_method_id,
    payment_method_name,
    status,
    amount,
    received_amount,
    change_amount,
    installments,
    external_reference,
    paid_at,
    created_at,
    updated_at
FROM mv_receipt_payments
WHERE sale_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListReceiptPaymentsBySaleID(ctx context.Context, saleID pgtype.UUID) ([]MvReceiptPayment, error) {
	rows, err := q.db.Query(ctx, listReceiptPaymentsBySaleID, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MvReceiptPayment{}
	for rows.Next() {
		var i MvReceiptPayment
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.PaymentMethodID,
			&i.PaymentMethodName,
			&i.Status,
			&i.Amount,
			&i.ReceivedAmount,
			&i.ChangeAmount,
			&i.Installments,
			&i.ExternalReference,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
