// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveOwnersForUpdate = `-- name: CountActiveOwnersForUpdate :one
WITH locked_owners AS (
    SELECT m.id
    FROM organization_memberships AS m
    JOIN membership_role_bindings AS b
      ON b.organization_id = m.organization_id
     AND b.membership_id = m.id
    JOIN roles AS r
      ON r.organization_id = b.organization_id
     AND r.id = b.role_id
    WHERE m.organization_id = $1
      AND m.status = 'ACTIVE'
      AND r.key = 'owner'
      AND r.is_system
      AND r.is_active
      AND b.store_id IS NULL
      AND (b.expires_at IS NULL OR b.expires_at > NOW())
    FOR UPDATE OF m, b
)
SELECT COUNT(DISTINCT id)::BIGINT AS owner_count
FROM locked_owners
`

func (q *Queries) CountActiveOwnersForUpdate(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOwnersForUpdate, organizationID)
	var owner_count int64
	err := row.Scan(&owner_count)
	return owner_count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO
    roles (
        organization_id,
        key,
        name,
        description,
        assignment_scope,
        is_system,
        is_mutable,
        created_by_membership_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    ) RETURNING id,
    organization_id,
    key,
    name,
    description,
    assignment_scope,
    is_system,
    is_mutable,
    is_active,
    created_by_membership_id,
    created_at,
    updated_at
`

type CreateRoleParams struct {
	OrganizationID        pgtype.UUID
	Key                   string
	Name                  string
	Description           pgtype.Text
	AssignmentScope       RoleAssignmentScope
	IsSystem              bool
	IsMutable             bool
	CreatedByMembershipID pgtype.UUID
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.OrganizationID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.AssignmentScope,
		arg.IsSystem,
		arg.IsMutable,
		arg.CreatedByMembershipID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.AssignmentScope,
		&i.IsSystem,
		&i.IsMutable,
		&i.IsActive,
		&i.CreatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoleBinding = `-- name: CreateRoleBinding :one
WITH
    organization_binding AS (
        INSERT INTO
            membership_role_bindings (
                organization_id,
                membership_id,
                role_id,
                store_id,
                created_by_membership_id,
                expires_at
            )
        SELECT $1, $2, $3, NULL, $4, CAST(
                $5 AS TIMESTAMPTZ
            )
        WHERE
            CAST($6 AS UUID) IS NULL ON CONFLICT (
                organization_id,
                membership_id,
                role_id
            )
        WHERE
            store_id IS NULL DO
        UPDATE
        SET
            expires_at = EXCLUDED.expires_at,
            created_by_membership_id = EXCLUDED.created_by_membership_id RETURNING id,
            organization_id,
            membership_id,
            role_id,
            store_id,
            created_by_membership_id,
            expires_at,
            created_at
    ),
    store_binding AS (
        INSERT INTO
            membership_role_bindings (
                organization_id,
                membership_id,
                role_id,
                store_id,
                created_by_membership_id,
                expires_at
            )
        SELECT $1, $2, $3, CAST($6 AS UUID), $4, CAST(
                $5 AS TIMESTAMPTZ
            )
        WHERE
            CAST($6 AS UUID) IS NOT NULL ON CONFLICT (
                organization_id,
                membership_id,
                role_id,
                store_id
            )
        WHERE
            store_id IS NOT NULL DO
        UPDATE
        SET
            expires_at = EXCLUDED.expires_at,
            created_by_membership_id = EXCLUDED.created_by_membership_id RETURNING id,
            organization_id,
            membership_id,
            role_id,
            store_id,
            created_by_membership_id,
            expires_at,
            created_at
    )
SELECT id, organization_id, membership_id, role_id, store_id, created_by_membership_id, expires_at, created_at
FROM organization_binding
UNION ALL
SELECT id, organization_id, membership_id, role_id, store_id, created_by_membership_id, expires_at, created_at
FROM store_binding
`

type CreateRoleBindingParams struct {
	OrganizationID        pgtype.UUID
	MembershipID          pgtype.UUID
	RoleID                pgtype.UUID
	CreatedByMembershipID pgtype.UUID
	ExpiresAt             pgtype.Timestamptz
	StoreID               pgtype.UUID
}

type CreateRoleBindingRow struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	MembershipID          pgtype.UUID
	RoleID                pgtype.UUID
	StoreID               pgtype.UUID
	CreatedByMembershipID pgtype.UUID
	ExpiresAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateRoleBinding(ctx context.Context, arg CreateRoleBindingParams) (CreateRoleBindingRow, error) {
	row := q.db.QueryRow(ctx, createRoleBinding,
		arg.OrganizationID,
		arg.MembershipID,
		arg.RoleID,
		arg.CreatedByMembershipID,
		arg.ExpiresAt,
		arg.StoreID,
	)
	var i CreateRoleBindingRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MembershipID,
		&i.RoleID,
		&i.StoreID,
		&i.CreatedByMembershipID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRoleBinding = `-- name: DeleteRoleBinding :one
DELETE FROM membership_role_bindings
WHERE
    organization_id = $1
    AND id = $2 RETURNING id,
    organization_id,
    membership_id,
    role_id,
    store_id,
    created_by_membership_id,
    expires_at,
    created_at
`

type DeleteRoleBindingParams struct {
	OrganizationID pgtype.UUID
	BindingID      pgtype.UUID
}

func (q *Queries) DeleteRoleBinding(ctx context.Context, arg DeleteRoleBindingParams) (MembershipRoleBinding, error) {
	row := q.db.QueryRow(ctx, deleteRoleBinding, arg.OrganizationID, arg.BindingID)
	var i MembershipRoleBinding
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.MembershipID,
		&i.RoleID,
		&i.StoreID,
		&i.CreatedByMembershipID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleForOrganization = `-- name: GetRoleForOrganization :one
SELECT
    id,
    organization_id,
    key,
    name,
    description,
    assignment_scope,
    is_system,
    is_mutable,
    is_active,
    created_by_membership_id,
    created_at,
    updated_at
FROM roles
WHERE
    organization_id = $1
    AND id = $2
`

type GetRoleForOrganizationParams struct {
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
}

func (q *Queries) GetRoleForOrganization(ctx context.Context, arg GetRoleForOrganizationParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleForOrganization, arg.OrganizationID, arg.RoleID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.AssignmentScope,
		&i.IsSystem,
		&i.IsMutable,
		&i.IsActive,
		&i.CreatedByMembershipID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemberRoleBindings = `-- name: ListMemberRoleBindings :many
SELECT
    b.id,
    b.organization_id,
    b.membership_id,
    b.role_id,
    b.store_id,
    b.created_by_membership_id,
    b.expires_at,
    b.created_at,
    r.key AS role_key,
    r.name AS role_name,
    r.assignment_scope,
    r.is_system,
    r.is_active,
    s.code AS store_code,
    s.name AS store_name
FROM
    membership_role_bindings AS b
    JOIN roles AS r ON r.organization_id = b.organization_id
    AND r.id = b.role_id
    LEFT JOIN stores AS s ON s.organization_id = b.organization_id
    AND s.id = b.store_id
WHERE
    b.organization_id = $1
    AND b.membership_id = $2
ORDER BY r.assignment_scope ASC, r.name ASC, s.name ASC NULLS FIRST, b.id ASC
`

type ListMemberRoleBindingsParams struct {
	OrganizationID pgtype.UUID
	MembershipID   pgtype.UUID
}

type ListMemberRoleBindingsRow struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	MembershipID          pgtype.UUID
	RoleID                pgtype.UUID
	StoreID               pgtype.UUID
	CreatedByMembershipID pgtype.UUID
	ExpiresAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	RoleKey               string
	RoleName              string
	AssignmentScope       RoleAssignmentScope
	IsSystem              bool
	IsActive              bool
	StoreCode             pgtype.Text
	StoreName             pgtype.Text
}

func (q *Queries) ListMemberRoleBindings(ctx context.Context, arg ListMemberRoleBindingsParams) ([]ListMemberRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, listMemberRoleBindings, arg.OrganizationID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberRoleBindingsRow{}
	for rows.Next() {
		var i ListMemberRoleBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.MembershipID,
			&i.RoleID,
			&i.StoreID,
			&i.CreatedByMembershipID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.RoleKey,
			&i.RoleName,
			&i.AssignmentScope,
			&i.IsSystem,
			&i.IsActive,
			&i.StoreCode,
			&i.StoreName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithScopes = `-- name: ListRolesWithScopes :many
SELECT
    r.id,
    r.organization_id,
    r.key,
    r.name,
    r.description,
    r.assignment_scope,
    r.is_system,
    r.is_mutable,
    r.is_active,
    r.created_by_membership_id,
    r.created_at,
    r.updated_at,
    ARRAY(
        SELECT role_scope.scope_code::TEXT
        FROM role_scopes AS role_scope
        WHERE role_scope.organization_id = r.organization_id
          AND role_scope.role_id = r.id
        ORDER BY role_scope.scope_code
    )::TEXT[] AS scope_codes
FROM roles AS r
WHERE r.organization_id = $1
ORDER BY r.name ASC, r.id ASC
`

type ListRolesWithScopesRow struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	Key                   string
	Name                  string
	Description           pgtype.Text
	AssignmentScope       RoleAssignmentScope
	IsSystem              bool
	IsMutable             bool
	IsActive              bool
	CreatedByMembershipID pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ScopeCodes            []string
}

func (q *Queries) ListRolesWithScopes(ctx context.Context, organizationID pgtype.UUID) ([]ListRolesWithScopesRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithScopes, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesWithScopesRow{}
	for rows.Next() {
		var i ListRolesWithScopesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.AssignmentScope,
			&i.IsSystem,
			&i.IsMutable,
			&i.IsActive,
			&i.CreatedByMembershipID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScopeCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoleForScopeChange = `-- name: LockRoleForScopeChange :one
SELECT
    id,
    organization_id,
    is_mutable
FROM roles
WHERE organization_id = $1
  AND id = $2
  AND is_mutable
FOR UPDATE
`

type LockRoleForScopeChangeParams struct {
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
}

type LockRoleForScopeChangeRow struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	IsMutable      bool
}

func (q *Queries) LockRoleForScopeChange(ctx context.Context, arg LockRoleForScopeChangeParams) (LockRoleForScopeChangeRow, error) {
	row := q.db.QueryRow(ctx, lockRoleForScopeChange, arg.OrganizationID, arg.RoleID)
	var i LockRoleForScopeChangeRow
	err := row.Scan(&i.ID, &i.OrganizationID, &i.IsMutable)
	return i, err
}

const replaceRoleScopes = `-- name: ReplaceRoleScopes :many
WITH deleted_scopes AS (
    DELETE FROM role_scopes
    WHERE organization_id = $1
      AND role_id = $2
      AND scope_code <> ALL(CAST($3 AS TEXT[]))
), requested_scopes AS (
    SELECT DISTINCT UNNEST(CAST($3 AS TEXT[])) AS scope_code
)
INSERT INTO role_scopes (
    organization_id,
    role_id,
    scope_code
)
SELECT
    $1,
    $2,
    requested_scopes.scope_code
FROM requested_scopes
ORDER BY requested_scopes.scope_code
ON CONFLICT (organization_id, role_id, scope_code) DO NOTHING
RETURNING
    organization_id,
    role_id,
    scope_code,
    created_at
`

type ReplaceRoleScopesParams struct {
	OrganizationID pgtype.UUID
	RoleID         pgtype.UUID
	ScopeCodes     []string
}

func (q *Queries) ReplaceRoleScopes(ctx context.Context, arg ReplaceRoleScopesParams) ([]RoleScope, error) {
	rows, err := q.db.Query(ctx, replaceRoleScopes, arg.OrganizationID, arg.RoleID, arg.ScopeCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleScope{}
	for rows.Next() {
		var i RoleScope
		if err := rows.Scan(
			&i.OrganizationID,
			&i.RoleID,
			&i.ScopeCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveEffectiveScopes = `-- name: ResolveEffectiveScopes :one
WITH valid_context AS (
    SELECT
        m.organization_id,
        m.id AS membership_id,
        CAST($1 AS auth_context_kind) AS context_kind,
        CAST($2 AS UUID) AS store_id
    FROM organization_memberships AS m
    JOIN users AS u ON u.id = m.user_id
    JOIN organizations AS o ON o.id = m.organization_id
    LEFT JOIN stores AS s
      ON s.organization_id = m.organization_id
     AND s.id = CAST($2 AS UUID)
    WHERE m.organization_id = $3
      AND m.id = $4
      AND m.user_id = $5
      AND u.status = 'ACTIVE'
      AND o.status = 'ACTIVE'
      AND m.status = 'ACTIVE'
      AND (
          (
              CAST($1 AS auth_context_kind) = 'ORGANIZATION'
              AND CAST($2 AS UUID) IS NULL
          )
          OR (
              CAST($1 AS auth_context_kind) = 'STORE'
              AND CAST($2 AS UUID) IS NOT NULL
              AND s.status = 'ACTIVE'
          )
      )
), effective_roles AS (
    SELECT DISTINCT
        r.organization_id,
        r.id,
        r.key
    FROM valid_context AS c
    JOIN membership_role_bindings AS b
      ON b.organization_id = c.organization_id
     AND b.membership_id = c.membership_id
    JOIN roles AS r
      ON r.organization_id = b.organization_id
     AND r.id = b.role_id
    WHERE r.is_active
      AND (b.expires_at IS NULL OR b.expires_at > NOW())
      AND (
          (
              c.context_kind = 'ORGANIZATION'
              AND r.assignment_scope = 'ORGANIZATION'
              AND b.store_id IS NULL
          )
          OR (
              c.context_kind = 'STORE'
              AND (
                  (
                      r.assignment_scope = 'ORGANIZATION'
                      AND b.store_id IS NULL
                  )
                  OR (
                      r.assignment_scope = 'STORE'
                      AND b.store_id = c.store_id
                  )
              )
          )
      )
)
SELECT
    ARRAY(
        SELECT r.key
        FROM effective_roles AS r
        ORDER BY r.key
    )::TEXT[] AS role_keys,
    ARRAY(
        SELECT DISTINCT rs.scope_code
        FROM effective_roles AS r
        JOIN role_scopes AS rs
          ON rs.organization_id = r.organization_id
         AND rs.role_id = r.id
        JOIN permission_scopes AS ps ON ps.code = rs.scope_code
        WHERE c.context_kind = 'STORE'
           OR ps.scope_level = 'ORGANIZATION'
        ORDER BY rs.scope_code
    )::TEXT[] AS scope_codes
FROM valid_context AS c
`

type ResolveEffectiveScopesParams struct {
	ContextKind    AuthContextKind
	StoreID        pgtype.UUID
	OrganizationID pgtype.UUID
	MembershipID   pgtype.UUID
	UserID         pgtype.UUID
}

type ResolveEffectiveScopesRow struct {
	RoleKeys   []string
	ScopeCodes []string
}

func (q *Queries) ResolveEffectiveScopes(ctx context.Context, arg ResolveEffectiveScopesParams) (ResolveEffectiveScopesRow, error) {
	row := q.db.QueryRow(ctx, resolveEffectiveScopes,
		arg.ContextKind,
		arg.StoreID,
		arg.OrganizationID,
		arg.MembershipID,
		arg.UserID,
	)
	var i ResolveEffectiveScopesRow
	err := row.Scan(&i.RoleKeys, &i.ScopeCodes)
	return i, err
}
