// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSale = `-- name: CancelSale :one
UPDATE sales
SET
    status = 'CANCELLED',
    cancelled_at = NOW()
WHERE id = $1
  AND status = 'OPEN'
RETURNING
    id,
    number,
    status,
    subtotal,
    discount,
    addition,
    total,
    opened_at,
    completed_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
`

type CancelSaleRow struct {
	ID             pgtype.UUID
	Number         int64
	Status         SaleStatus
	Subtotal       pgtype.Numeric
	Discount       pgtype.Numeric
	Addition       pgtype.Numeric
	Total          pgtype.Numeric
	OpenedAt       pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey string
}

func (q *Queries) CancelSale(ctx context.Context, id pgtype.UUID) (CancelSaleRow, error) {
	row := q.db.QueryRow(ctx, cancelSale, id)
	var i CancelSaleRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Addition,
		&i.Total,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const countSales = `-- name: CountSales :one
SELECT COUNT(*)
FROM sales
WHERE (
    CAST($1 AS sale_status) IS NULL
    OR status = CAST($1 AS sale_status)
)
`

func (q *Queries) CountSales(ctx context.Context, status NullSaleStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countSales, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSale = `-- name: CreateSale :one
WITH inserted AS (
    INSERT INTO sales (
        status,
        subtotal,
        discount,
        addition,
        total,
        idempotency_key
    )
    VALUES (
        'OPEN',
        0,
        0,
        0,
        0,
        $1
    )
    ON CONFLICT (idempotency_key) DO NOTHING
    RETURNING
        id,
        number,
        status,
        subtotal,
        discount,
        addition,
        total,
        opened_at,
        completed_at,
        cancelled_at,
        created_at,
        updated_at,
        idempotency_key
)
SELECT
    id,
    number,
    status,
    subtotal,
    discount,
    addition,
    total,
    opened_at,
    completed_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM inserted
UNION ALL
SELECT
    id,
    number,
    status,
    subtotal,
    discount,
    addition,
    total,
    opened_at,
    completed_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM sales
WHERE idempotency_key = $1
LIMIT 1
`

type CreateSaleRow struct {
	ID             pgtype.UUID
	Number         int64
	Status         SaleStatus
	Subtotal       pgtype.Numeric
	Discount       pgtype.Numeric
	Addition       pgtype.Numeric
	Total          pgtype.Numeric
	OpenedAt       pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey string
}

func (q *Queries) CreateSale(ctx context.Context, idempotencyKey string) (CreateSaleRow, error) {
	row := q.db.QueryRow(ctx, createSale, idempotencyKey)
	var i CreateSaleRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Addition,
		&i.Total,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (
    sale_id,
    product_id,
    product_name,
    product_sku,
    unit_price,
    quantity,
    discount,
    total
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING
    id,
    sale_id,
    product_id,
    product_name,
    product_sku,
    unit_price,
    quantity,
    discount,
    total,
    created_at
`

type CreateSaleItemParams struct {
	SaleID      pgtype.UUID
	ProductID   pgtype.UUID
	ProductName string
	ProductSKU  string
	UnitPrice   pgtype.Numeric
	Quantity    pgtype.Numeric
	Discount    pgtype.Numeric
	Total       pgtype.Numeric
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.ProductName,
		arg.ProductSKU,
		arg.UnitPrice,
		arg.Quantity,
		arg.Discount,
		arg.Total,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductSKU,
		&i.UnitPrice,
		&i.Quantity,
		&i.Discount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSaleItem = `-- name: DeleteSaleItem :one
DELETE FROM sale_items
WHERE sale_id = $1
  AND id = $2
RETURNING
    id,
    sale_id,
    product_id,
    product_name,
    product_sku,
    unit_price,
    quantity,
    discount,
    total,
    created_at
`

type DeleteSaleItemParams struct {
	SaleID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) DeleteSaleItem(ctx context.Context, arg DeleteSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, deleteSaleItem, arg.SaleID, arg.ID)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductSKU,
		&i.UnitPrice,
		&i.Quantity,
		&i.Discount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getSaleByID = `-- name: GetSaleByID :one
SELECT
    id,
    number,
    status,
    subtotal,
    discount,
    addition,
    total,
    opened_at,
    completed_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM sales
WHERE id = $1
LIMIT 1
`

type GetSaleByIDRow struct {
	ID             pgtype.UUID
	Number         int64
	Status         SaleStatus
	Subtotal       pgtype.Numeric
	Discount       pgtype.Numeric
	Addition       pgtype.Numeric
	Total          pgtype.Numeric
	OpenedAt       pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey string
}

func (q *Queries) GetSaleByID(ctx context.Context, id pgtype.UUID) (GetSaleByIDRow, error) {
	row := q.db.QueryRow(ctx, getSaleByID, id)
	var i GetSaleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Addition,
		&i.Total,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getSaleItemByID = `-- name: GetSaleItemByID :one
SELECT
    id,
    sale_id,
    product_id,
    product_name,
    product_sku,
    unit_price,
    quantity,
    discount,
    total,
    created_at
FROM sale_items
WHERE sale_id = $1
  AND id = $2
LIMIT 1
`

type GetSaleItemByIDParams struct {
	SaleID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetSaleItemByID(ctx context.Context, arg GetSaleItemByIDParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, getSaleItemByID, arg.SaleID, arg.ID)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductSKU,
		&i.UnitPrice,
		&i.Quantity,
		&i.Discount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleItemsBySaleID = `-- name: ListSaleItemsBySaleID :many
SELECT
    id,
    sale_id,
    product_id,
    product_name,
    product_sku,
    unit_price,
    quantity,
    discount,
    total,
    created_at
FROM sale_items
WHERE sale_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListSaleItemsBySaleID(ctx context.Context, saleID pgtype.UUID) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, listSaleItemsBySaleID, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SaleItem{}
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSKU,
			&i.UnitPrice,
			&i.Quantity,
			&i.Discount,
			&i.Total,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT
    id,
    number,
    status,
    subtotal,
    discount,
    addition,
    total,
    opened_at,
    completed_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM sales
WHERE (
    CAST($1 AS sale_status) IS NULL
    OR status = CAST($1 AS sale_status)
)
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListSalesParams struct {
	Status     NullSaleStatus
	PageOffset int32
	PageSize   int32
}

type ListSalesRow struct {
	ID             pgtype.UUID
	Number         int64
	Status         SaleStatus
	Subtotal       pgtype.Numeric
	Discount       pgtype.Numeric
	Addition       pgtype.Numeric
	Total          pgtype.Numeric
	OpenedAt       pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey string
}

func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, arg.Status, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRow{}
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Status,
			&i.Subtotal,
			&i.Discount,
			&i.Addition,
			&i.Total,
			&i.OpenedAt,
			&i.CompletedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSaleByID = `-- name: LockSaleByID :one
SELECT
    id,
    number,
    status,
    subtotal,
    discount,
    addition,
    total,
    opened_at,
    completed_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
FROM sales
WHERE id = $1
FOR UPDATE
`

type LockSaleByIDRow struct {
	ID             pgtype.UUID
	Number         int64
	Status         SaleStatus
	Subtotal       pgtype.Numeric
	Discount       pgtype.Numeric
	Addition       pgtype.Numeric
	Total          pgtype.Numeric
	OpenedAt       pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey string
}

func (q *Queries) LockSaleByID(ctx context.Context, id pgtype.UUID) (LockSaleByIDRow, error) {
	row := q.db.QueryRow(ctx, lockSaleByID, id)
	var i LockSaleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Addition,
		&i.Total,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const recalculateSaleTotals = `-- name: RecalculateSaleTotals :one
UPDATE sales
SET
    subtotal = $1,
    discount = $2,
    addition = $3,
    total = $4
WHERE id = $5
  AND status = 'OPEN'
RETURNING
    id,
    number,
    status,
    subtotal,
    discount,
    addition,
    total,
    opened_at,
    completed_at,
    cancelled_at,
    created_at,
    updated_at,
    idempotency_key
`

type RecalculateSaleTotalsParams struct {
	Subtotal pgtype.Numeric
	Discount pgtype.Numeric
	Addition pgtype.Numeric
	Total    pgtype.Numeric
	ID       pgtype.UUID
}

type RecalculateSaleTotalsRow struct {
	ID             pgtype.UUID
	Number         int64
	Status         SaleStatus
	Subtotal       pgtype.Numeric
	Discount       pgtype.Numeric
	Addition       pgtype.Numeric
	Total          pgtype.Numeric
	OpenedAt       pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	IdempotencyKey string
}

func (q *Queries) RecalculateSaleTotals(ctx context.Context, arg RecalculateSaleTotalsParams) (RecalculateSaleTotalsRow, error) {
	row := q.db.QueryRow(ctx, recalculateSaleTotals,
		arg.Subtotal,
		arg.Discount,
		arg.Addition,
		arg.Total,
		arg.ID,
	)
	var i RecalculateSaleTotalsRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Addition,
		&i.Total,
		&i.OpenedAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const updateSaleItem = `-- name: UpdateSaleItem :one
UPDATE sale_items
SET
    quantity = $1,
    discount = $2,
    total = $3
WHERE sale_id = $4
  AND id = $5
RETURNING
    id,
    sale_id,
    product_id,
    product_name,
    product_sku,
    unit_price,
    quantity,
    discount,
    total,
    created_at
`

type UpdateSaleItemParams struct {
	Quantity pgtype.Numeric
	Discount pgtype.Numeric
	Total    pgtype.Numeric
	SaleID   pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) UpdateSaleItem(ctx context.Context, arg UpdateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, updateSaleItem,
		arg.Quantity,
		arg.Discount,
		arg.Total,
		arg.SaleID,
		arg.ID,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductSKU,
		&i.UnitPrice,
		&i.Quantity,
		&i.Discount,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}
