// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAndReplaceRefreshToken = `-- name: ConsumeAndReplaceRefreshToken :one
UPDATE auth_refresh_tokens
SET
    consumed_at = NOW(),
    replaced_by_token_id = $1
WHERE session_id = $2
  AND id = $3
  AND consumed_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > NOW()
RETURNING
    id,
    session_id,
    parent_token_id,
    replaced_by_token_id,
    expires_at,
    consumed_at,
    revoked_at,
    created_at
`

type ConsumeAndReplaceRefreshTokenParams struct {
	ReplacedByTokenID pgtype.UUID
	SessionID         pgtype.UUID
	ID                pgtype.UUID
}

type ConsumeAndReplaceRefreshTokenRow struct {
	ID                pgtype.UUID
	SessionID         pgtype.UUID
	ParentTokenID     pgtype.UUID
	ReplacedByTokenID pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
	ConsumedAt        pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) ConsumeAndReplaceRefreshToken(ctx context.Context, arg ConsumeAndReplaceRefreshTokenParams) (ConsumeAndReplaceRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, consumeAndReplaceRefreshToken, arg.ReplacedByTokenID, arg.SessionID, arg.ID)
	var i ConsumeAndReplaceRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentTokenID,
		&i.ReplacedByTokenID,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    user_id,
    client_id,
    device_name,
    user_agent,
    ip_address,
    context_kind,
    current_organization_id,
    current_membership_id,
    current_store_id,
    idle_expires_at,
    absolute_expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING
    id,
    user_id,
    status,
    client_id,
    device_name,
    user_agent,
    ip_address,
    context_kind,
    current_organization_id,
    current_membership_id,
    current_store_id,
    idle_expires_at,
    absolute_expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    created_at,
    updated_at
`

type CreateAuthSessionParams struct {
	UserID                pgtype.UUID
	ClientID              string
	DeviceName            pgtype.Text
	UserAgent             pgtype.Text
	IpAddress             *netip.Addr
	ContextKind           AuthContextKind
	CurrentOrganizationID pgtype.UUID
	CurrentMembershipID   pgtype.UUID
	CurrentStoreID        pgtype.UUID
	IdleExpiresAt         pgtype.Timestamptz
	AbsoluteExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.UserID,
		arg.ClientID,
		arg.DeviceName,
		arg.UserAgent,
		arg.IpAddress,
		arg.ContextKind,
		arg.CurrentOrganizationID,
		arg.CurrentMembershipID,
		arg.CurrentStoreID,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ClientID,
		&i.DeviceName,
		&i.UserAgent,
		&i.IpAddress,
		&i.ContextKind,
		&i.CurrentOrganizationID,
		&i.CurrentMembershipID,
		&i.CurrentStoreID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO auth_refresh_tokens (
    session_id,
    parent_token_id,
    secret_hash,
    expires_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    session_id,
    parent_token_id,
    replaced_by_token_id,
    secret_hash,
    expires_at,
    consumed_at,
    revoked_at,
    created_at
`

type CreateRefreshTokenParams struct {
	SessionID     pgtype.UUID
	ParentTokenID pgtype.UUID
	SecretHash    []byte
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.SessionID,
		arg.ParentTokenID,
		arg.SecretHash,
		arg.ExpiresAt,
	)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentTokenID,
		&i.ReplacedByTokenID,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireSessions = `-- name: ExpireSessions :many
UPDATE auth_sessions
SET
    status = 'EXPIRED',
    revoked_at = NOW(),
    revoke_reason = 'session_expired'
WHERE status = 'ACTIVE'
  AND (
      idle_expires_at <= NOW()
      OR absolute_expires_at <= NOW()
  )
RETURNING
    id,
    user_id,
    current_organization_id,
    current_membership_id,
    current_store_id,
    status,
    revoked_at,
    revoke_reason
`

type ExpireSessionsRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	CurrentOrganizationID pgtype.UUID
	CurrentMembershipID   pgtype.UUID
	CurrentStoreID        pgtype.UUID
	Status                AuthSessionStatus
	RevokedAt             pgtype.Timestamptz
	RevokeReason          pgtype.Text
}

func (q *Queries) ExpireSessions(ctx context.Context) ([]ExpireSessionsRow, error) {
	rows, err := q.db.Query(ctx, expireSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpireSessionsRow{}
	for rows.Next() {
		var i ExpireSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrentOrganizationID,
			&i.CurrentMembershipID,
			&i.CurrentStoreID,
			&i.Status,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthSessionByID = `-- name: GetAuthSessionByID :one
SELECT
    id,
    user_id,
    status,
    client_id,
    device_name,
    user_agent,
    ip_address,
    context_kind,
    current_organization_id,
    current_membership_id,
    current_store_id,
    idle_expires_at,
    absolute_expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    created_at,
    updated_at
FROM auth_sessions
WHERE id = $1
`

func (q *Queries) GetAuthSessionByID(ctx context.Context, id pgtype.UUID) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ClientID,
		&i.DeviceName,
		&i.UserAgent,
		&i.IpAddress,
		&i.ContextKind,
		&i.CurrentOrganizationID,
		&i.CurrentMembershipID,
		&i.CurrentStoreID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthSessionForUpdate = `-- name: GetAuthSessionForUpdate :one
SELECT
    s.id,
    s.user_id,
    s.status,
    s.client_id,
    s.device_name,
    s.user_agent,
    s.ip_address,
    s.context_kind,
    s.current_organization_id,
    s.current_membership_id,
    s.current_store_id,
    s.idle_expires_at,
    s.absolute_expires_at,
    s.last_seen_at,
    s.revoked_at,
    s.revoke_reason,
    s.created_at,
    s.updated_at,
    u.status AS user_status,
    u.password_version,
    o.status AS organization_status,
    o.authorization_version AS organization_authorization_version,
    m.status AS membership_status,
    m.authorization_version AS membership_authorization_version,
    st.status AS store_status
FROM auth_sessions AS s
JOIN users AS u ON u.id = s.user_id
LEFT JOIN organizations AS o ON o.id = s.current_organization_id
LEFT JOIN organization_memberships AS m
  ON m.organization_id = s.current_organization_id
 AND m.id = s.current_membership_id
 AND m.user_id = s.user_id
LEFT JOIN stores AS st
  ON st.organization_id = s.current_organization_id
 AND st.id = s.current_store_id
WHERE s.id = $1
FOR UPDATE OF s
`

type GetAuthSessionForUpdateRow struct {
	ID                               pgtype.UUID
	UserID                           pgtype.UUID
	Status                           AuthSessionStatus
	ClientID                         string
	DeviceName                       pgtype.Text
	UserAgent                        pgtype.Text
	IpAddress                        *netip.Addr
	ContextKind                      AuthContextKind
	CurrentOrganizationID            pgtype.UUID
	CurrentMembershipID              pgtype.UUID
	CurrentStoreID                   pgtype.UUID
	IdleExpiresAt                    pgtype.Timestamptz
	AbsoluteExpiresAt                pgtype.Timestamptz
	LastSeenAt                       pgtype.Timestamptz
	RevokedAt                        pgtype.Timestamptz
	RevokeReason                     pgtype.Text
	CreatedAt                        pgtype.Timestamptz
	UpdatedAt                        pgtype.Timestamptz
	UserStatus                       UserStatus
	PasswordVersion                  int64
	OrganizationStatus               NullOrganizationStatus
	OrganizationAuthorizationVersion pgtype.Int8
	MembershipStatus                 NullMembershipStatus
	MembershipAuthorizationVersion   pgtype.Int8
	StoreStatus                      NullStoreStatus
}

func (q *Queries) GetAuthSessionForUpdate(ctx context.Context, sessionID pgtype.UUID) (GetAuthSessionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionForUpdate, sessionID)
	var i GetAuthSessionForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ClientID,
		&i.DeviceName,
		&i.UserAgent,
		&i.IpAddress,
		&i.ContextKind,
		&i.CurrentOrganizationID,
		&i.CurrentMembershipID,
		&i.CurrentStoreID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserStatus,
		&i.PasswordVersion,
		&i.OrganizationStatus,
		&i.OrganizationAuthorizationVersion,
		&i.MembershipStatus,
		&i.MembershipAuthorizationVersion,
		&i.StoreStatus,
	)
	return i, err
}

const getAuthSessionState = `-- name: GetAuthSessionState :one
SELECT
    s.id,
    s.user_id,
    s.status,
    s.client_id,
    s.context_kind,
    s.current_organization_id,
    s.current_membership_id,
    s.current_store_id,
    s.idle_expires_at,
    s.absolute_expires_at,
    s.last_seen_at,
    u.status AS user_status,
    u.password_version,
    o.status AS organization_status,
    o.authorization_version AS organization_authorization_version,
    m.status AS membership_status,
    m.authorization_version AS membership_authorization_version,
    st.status AS store_status
FROM auth_sessions AS s
JOIN users AS u ON u.id = s.user_id
LEFT JOIN organizations AS o ON o.id = s.current_organization_id
LEFT JOIN organization_memberships AS m
  ON m.organization_id = s.current_organization_id
 AND m.id = s.current_membership_id
 AND m.user_id = s.user_id
LEFT JOIN stores AS st
  ON st.organization_id = s.current_organization_id
 AND st.id = s.current_store_id
WHERE s.id = $1
`

type GetAuthSessionStateRow struct {
	ID                               pgtype.UUID
	UserID                           pgtype.UUID
	Status                           AuthSessionStatus
	ClientID                         string
	ContextKind                      AuthContextKind
	CurrentOrganizationID            pgtype.UUID
	CurrentMembershipID              pgtype.UUID
	CurrentStoreID                   pgtype.UUID
	IdleExpiresAt                    pgtype.Timestamptz
	AbsoluteExpiresAt                pgtype.Timestamptz
	LastSeenAt                       pgtype.Timestamptz
	UserStatus                       UserStatus
	PasswordVersion                  int64
	OrganizationStatus               NullOrganizationStatus
	OrganizationAuthorizationVersion pgtype.Int8
	MembershipStatus                 NullMembershipStatus
	MembershipAuthorizationVersion   pgtype.Int8
	StoreStatus                      NullStoreStatus
}

func (q *Queries) GetAuthSessionState(ctx context.Context, sessionID pgtype.UUID) (GetAuthSessionStateRow, error) {
	row := q.db.QueryRow(ctx, getAuthSessionState, sessionID)
	var i GetAuthSessionStateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ClientID,
		&i.ContextKind,
		&i.CurrentOrganizationID,
		&i.CurrentMembershipID,
		&i.CurrentStoreID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.UserStatus,
		&i.PasswordVersion,
		&i.OrganizationStatus,
		&i.OrganizationAuthorizationVersion,
		&i.MembershipStatus,
		&i.MembershipAuthorizationVersion,
		&i.StoreStatus,
	)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT
    id,
    session_id,
    parent_token_id,
    replaced_by_token_id,
    secret_hash,
    expires_at,
    consumed_at,
    revoked_at,
    created_at
FROM auth_refresh_tokens
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, id pgtype.UUID) (AuthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, id)
	var i AuthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentTokenID,
		&i.ReplacedByTokenID,
		&i.SecretHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT
    id,
    user_id,
    status,
    client_id,
    device_name,
    user_agent,
    ip_address,
    context_kind,
    current_organization_id,
    current_membership_id,
    current_store_id,
    idle_expires_at,
    absolute_expires_at,
    last_seen_at,
    revoked_at,
    revoke_reason,
    created_at,
    updated_at
FROM auth_sessions
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID pgtype.UUID) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthSession{}
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.ClientID,
			&i.DeviceName,
			&i.UserAgent,
			&i.IpAddress,
			&i.ContextKind,
			&i.CurrentOrganizationID,
			&i.CurrentMembershipID,
			&i.CurrentStoreID,
			&i.IdleExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionCompromised = `-- name: MarkSessionCompromised :one
UPDATE auth_sessions
SET
    status = 'COMPROMISED',
    revoked_at = NOW(),
    revoke_reason = $1
WHERE id = $2
  AND status = 'ACTIVE'
RETURNING
    id,
    user_id,
    status,
    current_organization_id,
    current_membership_id,
    current_store_id,
    revoked_at,
    revoke_reason,
    updated_at
`

type MarkSessionCompromisedParams struct {
	RevokeReason pgtype.Text
	SessionID    pgtype.UUID
}

type MarkSessionCompromisedRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Status                AuthSessionStatus
	CurrentOrganizationID pgtype.UUID
	CurrentMembershipID   pgtype.UUID
	CurrentStoreID        pgtype.UUID
	RevokedAt             pgtype.Timestamptz
	RevokeReason          pgtype.Text
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) MarkSessionCompromised(ctx context.Context, arg MarkSessionCompromisedParams) (MarkSessionCompromisedRow, error) {
	row := q.db.QueryRow(ctx, markSessionCompromised, arg.RevokeReason, arg.SessionID)
	var i MarkSessionCompromisedRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CurrentOrganizationID,
		&i.CurrentMembershipID,
		&i.CurrentStoreID,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :many
UPDATE auth_sessions
SET
    status = 'REVOKED',
    revoked_at = NOW(),
    revoke_reason = $1
WHERE user_id = $2
  AND status = 'ACTIVE'
RETURNING
    id,
    user_id,
    current_organization_id,
    current_membership_id,
    current_store_id,
    status,
    revoked_at,
    revoke_reason
`

type RevokeAllUserSessionsParams struct {
	RevokeReason pgtype.Text
	UserID       pgtype.UUID
}

type RevokeAllUserSessionsRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	CurrentOrganizationID pgtype.UUID
	CurrentMembershipID   pgtype.UUID
	CurrentStoreID        pgtype.UUID
	Status                AuthSessionStatus
	RevokedAt             pgtype.Timestamptz
	RevokeReason          pgtype.Text
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) ([]RevokeAllUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, revokeAllUserSessions, arg.RevokeReason, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeAllUserSessionsRow{}
	for rows.Next() {
		var i RevokeAllUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrentOrganizationID,
			&i.CurrentMembershipID,
			&i.CurrentStoreID,
			&i.Status,
			&i.RevokedAt,
			&i.RevokeReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :one
UPDATE auth_sessions
SET
    status = 'REVOKED',
    revoked_at = NOW(),
    revoke_reason = $1
WHERE id = $2
  AND user_id = $3
  AND status = 'ACTIVE'
RETURNING
    id,
    user_id,
    status,
    current_organization_id,
    current_membership_id,
    current_store_id,
    revoked_at,
    revoke_reason,
    updated_at
`

type RevokeSessionParams struct {
	RevokeReason pgtype.Text
	SessionID    pgtype.UUID
	UserID       pgtype.UUID
}

type RevokeSessionRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Status                AuthSessionStatus
	CurrentOrganizationID pgtype.UUID
	CurrentMembershipID   pgtype.UUID
	CurrentStoreID        pgtype.UUID
	RevokedAt             pgtype.Timestamptz
	RevokeReason          pgtype.Text
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (RevokeSessionRow, error) {
	row := q.db.QueryRow(ctx, revokeSession, arg.RevokeReason, arg.SessionID, arg.UserID)
	var i RevokeSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.CurrentOrganizationID,
		&i.CurrentMembershipID,
		&i.CurrentStoreID,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionRefreshTokens = `-- name: RevokeSessionRefreshTokens :many
UPDATE auth_refresh_tokens
SET revoked_at = NOW()
WHERE session_id = $1
  AND revoked_at IS NULL
RETURNING
    id,
    session_id,
    parent_token_id,
    replaced_by_token_id,
    expires_at,
    consumed_at,
    revoked_at,
    created_at
`

type RevokeSessionRefreshTokensRow struct {
	ID                pgtype.UUID
	SessionID         pgtype.UUID
	ParentTokenID     pgtype.UUID
	ReplacedByTokenID pgtype.UUID
	ExpiresAt         pgtype.Timestamptz
	ConsumedAt        pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) RevokeSessionRefreshTokens(ctx context.Context, sessionID pgtype.UUID) ([]RevokeSessionRefreshTokensRow, error) {
	rows, err := q.db.Query(ctx, revokeSessionRefreshTokens, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevokeSessionRefreshTokensRow{}
	for rows.Next() {
		var i RevokeSessionRefreshTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentTokenID,
			&i.ReplacedByTokenID,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :one
UPDATE auth_sessions
SET
    last_seen_at = NOW(),
    idle_expires_at = LEAST($1, absolute_expires_at)
WHERE id = $2
  AND user_id = $3
  AND status = 'ACTIVE'
  AND idle_expires_at > NOW()
  AND absolute_expires_at > NOW()
RETURNING
    id,
    user_id,
    idle_expires_at,
    absolute_expires_at,
    last_seen_at,
    updated_at
`

type TouchSessionParams struct {
	IdleExpiresAt pgtype.Timestamptz
	SessionID     pgtype.UUID
	UserID        pgtype.UUID
}

type TouchSessionRow struct {
	ID                pgtype.UUID
	UserID            pgtype.UUID
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (TouchSessionRow, error) {
	row := q.db.QueryRow(ctx, touchSession, arg.IdleExpiresAt, arg.SessionID, arg.UserID)
	var i TouchSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionContext = `-- name: UpdateSessionContext :one
UPDATE auth_sessions
SET
    context_kind = $1,
    current_organization_id = $2,
    current_membership_id = $3,
    current_store_id = $4
WHERE id = $5
  AND user_id = $6
  AND status = 'ACTIVE'
  AND idle_expires_at > NOW()
  AND absolute_expires_at > NOW()
RETURNING
    id,
    user_id,
    status,
    context_kind,
    current_organization_id,
    current_membership_id,
    current_store_id,
    idle_expires_at,
    absolute_expires_at,
    updated_at
`

type UpdateSessionContextParams struct {
	ContextKind           AuthContextKind
	CurrentOrganizationID pgtype.UUID
	CurrentMembershipID   pgtype.UUID
	CurrentStoreID        pgtype.UUID
	SessionID             pgtype.UUID
	UserID                pgtype.UUID
}

type UpdateSessionContextRow struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Status                AuthSessionStatus
	ContextKind           AuthContextKind
	CurrentOrganizationID pgtype.UUID
	CurrentMembershipID   pgtype.UUID
	CurrentStoreID        pgtype.UUID
	IdleExpiresAt         pgtype.Timestamptz
	AbsoluteExpiresAt     pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdateSessionContext(ctx context.Context, arg UpdateSessionContextParams) (UpdateSessionContextRow, error) {
	row := q.db.QueryRow(ctx, updateSessionContext,
		arg.ContextKind,
		arg.CurrentOrganizationID,
		arg.CurrentMembershipID,
		arg.CurrentStoreID,
		arg.SessionID,
		arg.UserID,
	)
	var i UpdateSessionContextRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.ContextKind,
		&i.CurrentOrganizationID,
		&i.CurrentMembershipID,
		&i.CurrentStoreID,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}
