// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stores.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveStores = `-- name: CountActiveStores :one
SELECT COUNT(*) FROM stores
WHERE organization_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) CountActiveStores(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveStores, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStoresForOrganization = `-- name: CountStoresForOrganization :one
SELECT COUNT(*)
FROM stores
WHERE organization_id = $1
  AND (CAST($2 AS store_status) IS NULL OR status = CAST($2 AS store_status))
  AND (CAST($3 AS TEXT) IS NULL
       OR name ILIKE '%' || CAST($3 AS TEXT) || '%'
       OR code ILIKE '%' || CAST($3 AS TEXT) || '%')
`

type CountStoresForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Status         NullStoreStatus
	Search         pgtype.Text
}

func (q *Queries) CountStoresForOrganization(ctx context.Context, arg CountStoresForOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStoresForOrganization, arg.OrganizationID, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
    organization_id,
    code,
    name,
    timezone,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING
    id,
    organization_id,
    code,
    name,
    status,
    timezone,
    created_by_user_id,
    archived_at,
    created_at,
    updated_at
`

type CreateStoreParams struct {
	OrganizationID  pgtype.UUID
	Code            string
	Name            string
	Timezone        string
	CreatedByUserID pgtype.UUID
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.OrganizationID,
		arg.Code,
		arg.Name,
		arg.Timezone,
		arg.CreatedByUserID,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreForOrganization = `-- name: GetStoreForOrganization :one
SELECT
    id,
    organization_id,
    code,
    name,
    status,
    timezone,
    created_by_user_id,
    archived_at,
    created_at,
    updated_at
FROM stores
WHERE organization_id = $1
  AND id = $2
`

type GetStoreForOrganizationParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
}

func (q *Queries) GetStoreForOrganization(ctx context.Context, arg GetStoreForOrganizationParams) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreForOrganization, arg.OrganizationID, arg.StoreID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasOpenSalesForStore = `-- name: HasOpenSalesForStore :one
SELECT EXISTS (
  SELECT 1 FROM sales
  WHERE organization_id = $1
    AND store_id = $2
    AND status = 'OPEN'
)
`

type HasOpenSalesForStoreParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
}

func (q *Queries) HasOpenSalesForStore(ctx context.Context, arg HasOpenSalesForStoreParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasOpenSalesForStore, arg.OrganizationID, arg.StoreID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listStoresForMembership = `-- name: ListStoresForMembership :many
SELECT
    s.id,
    s.organization_id,
    s.code,
    s.name,
    s.status,
    s.timezone,
    s.created_by_user_id,
    s.archived_at,
    s.created_at,
    s.updated_at
FROM organization_memberships AS m
JOIN organizations AS o ON o.id = m.organization_id
JOIN stores AS s ON s.organization_id = m.organization_id
WHERE m.organization_id = $1
  AND m.id = $2
  AND m.status = 'ACTIVE'
  AND o.status = 'ACTIVE'
  AND s.status = 'ACTIVE'
  AND (
      EXISTS (
          SELECT 1
          FROM membership_role_bindings AS b
          JOIN roles AS r
            ON r.organization_id = b.organization_id
           AND r.id = b.role_id
          JOIN role_scopes AS rs
            ON rs.organization_id = r.organization_id
           AND rs.role_id = r.id
          JOIN permission_scopes AS ps ON ps.code = rs.scope_code
          WHERE b.organization_id = m.organization_id
            AND b.membership_id = m.id
            AND b.store_id IS NULL
            AND r.assignment_scope = 'ORGANIZATION'
            AND r.is_active
            AND ps.scope_level = 'STORE'
            AND (b.expires_at IS NULL OR b.expires_at > NOW())
      )
      OR EXISTS (
          SELECT 1
          FROM membership_role_bindings AS b
          JOIN roles AS r
            ON r.organization_id = b.organization_id
           AND r.id = b.role_id
          JOIN role_scopes AS rs
            ON rs.organization_id = r.organization_id
           AND rs.role_id = r.id
          JOIN permission_scopes AS ps ON ps.code = rs.scope_code
          WHERE b.organization_id = m.organization_id
            AND b.membership_id = m.id
            AND b.store_id = s.id
            AND r.assignment_scope = 'STORE'
            AND r.is_active
            AND ps.scope_level = 'STORE'
            AND (b.expires_at IS NULL OR b.expires_at > NOW())
      )
  )
ORDER BY s.name ASC, s.id ASC
`

type ListStoresForMembershipParams struct {
	OrganizationID pgtype.UUID
	MembershipID   pgtype.UUID
}

func (q *Queries) ListStoresForMembership(ctx context.Context, arg ListStoresForMembershipParams) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStoresForMembership, arg.OrganizationID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.Timezone,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoresForOrganization = `-- name: ListStoresForOrganization :many
SELECT id, organization_id, code, name, status, timezone, created_by_user_id,
       archived_at, created_at, updated_at
FROM stores
WHERE organization_id = $1
  AND (CAST($2 AS store_status) IS NULL OR status = CAST($2 AS store_status))
  AND (CAST($3 AS TEXT) IS NULL
       OR name ILIKE '%' || CAST($3 AS TEXT) || '%'
       OR code ILIKE '%' || CAST($3 AS TEXT) || '%')
ORDER BY name ASC, id ASC
LIMIT $5 OFFSET $4
`

type ListStoresForOrganizationParams struct {
	OrganizationID pgtype.UUID
	Status         NullStoreStatus
	Search         pgtype.Text
	PageOffset     int32
	PageSize       int32
}

func (q *Queries) ListStoresForOrganization(ctx context.Context, arg ListStoresForOrganizationParams) ([]Store, error) {
	rows, err := q.db.Query(ctx, listStoresForOrganization,
		arg.OrganizationID,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.Timezone,
			&i.CreatedByUserID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockStoreForStatusChange = `-- name: LockStoreForStatusChange :one
SELECT id, organization_id, code, name, status, timezone, created_by_user_id,
       archived_at, created_at, updated_at
FROM stores
WHERE organization_id = $1 AND id = $2
FOR UPDATE
`

type LockStoreForStatusChangeParams struct {
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
}

func (q *Queries) LockStoreForStatusChange(ctx context.Context, arg LockStoreForStatusChangeParams) (Store, error) {
	row := q.db.QueryRow(ctx, lockStoreForStatusChange, arg.OrganizationID, arg.StoreID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET
    code = $1,
    name = $2,
    timezone = $3
WHERE organization_id = $4
  AND id = $5
RETURNING
    id,
    organization_id,
    code,
    name,
    status,
    timezone,
    created_by_user_id,
    archived_at,
    created_at,
    updated_at
`

type UpdateStoreParams struct {
	Code           string
	Name           string
	Timezone       string
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.Code,
		arg.Name,
		arg.Timezone,
		arg.OrganizationID,
		arg.StoreID,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStoreStatus = `-- name: UpdateStoreStatus :one
UPDATE stores
SET
    status = $1,
    archived_at = CASE
        WHEN $1::store_status = 'ARCHIVED' THEN NOW()
        ELSE NULL
    END
WHERE organization_id = $2
  AND id = $3
RETURNING
    id,
    organization_id,
    code,
    name,
    status,
    timezone,
    created_by_user_id,
    archived_at,
    created_at,
    updated_at
`

type UpdateStoreStatusParams struct {
	Status         StoreStatus
	OrganizationID pgtype.UUID
	StoreID        pgtype.UUID
}

func (q *Queries) UpdateStoreStatus(ctx context.Context, arg UpdateStoreStatusParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStoreStatus, arg.Status, arg.OrganizationID, arg.StoreID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Timezone,
		&i.CreatedByUserID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
