// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
WITH created_user AS (
    INSERT INTO users (
        email,
        email_normalized,
        display_name
    )
    VALUES (
        $1,
        $2,
        $3
    )
    RETURNING
        id,
        email,
        email_normalized,
        display_name,
        status,
        email_verified_at,
        password_version,
        last_login_at,
        created_at,
        updated_at
), created_password AS (
    INSERT INTO user_passwords (
        user_id,
        password_hash
    )
    SELECT
        id,
        $4
    FROM created_user
    RETURNING user_id
)
SELECT
    u.id,
    u.email,
    u.email_normalized,
    u.display_name,
    u.status,
    u.email_verified_at,
    u.password_version,
    u.last_login_at,
    u.created_at,
    u.updated_at
FROM created_user AS u
JOIN created_password AS p ON p.user_id = u.id
`

type CreateUserWithPasswordParams struct {
	Email           string
	EmailNormalized string
	DisplayName     string
	PasswordHash    string
}

type CreateUserWithPasswordRow struct {
	ID              pgtype.UUID
	Email           string
	EmailNormalized string
	DisplayName     string
	Status          UserStatus
	EmailVerifiedAt pgtype.Timestamptz
	PasswordVersion int64
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.Email,
		arg.EmailNormalized,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i CreateUserWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PasswordVersion,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    email_normalized,
    display_name,
    status,
    email_verified_at,
    password_version,
    last_login_at,
    created_at,
    updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PasswordVersion,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByNormalizedEmail = `-- name: GetUserByNormalizedEmail :one
SELECT
    u.id,
    u.email,
    u.email_normalized,
    u.display_name,
    u.status,
    u.email_verified_at,
    u.password_version,
    u.last_login_at,
    u.created_at,
    u.updated_at,
    p.password_hash,
    p.changed_at AS password_changed_at
FROM users AS u
JOIN user_passwords AS p ON p.user_id = u.id
WHERE u.email_normalized = $1
LIMIT 1
`

type GetUserByNormalizedEmailRow struct {
	ID                pgtype.UUID
	Email             string
	EmailNormalized   string
	DisplayName       string
	Status            UserStatus
	EmailVerifiedAt   pgtype.Timestamptz
	PasswordVersion   int64
	LastLoginAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByNormalizedEmail(ctx context.Context, emailNormalized string) (GetUserByNormalizedEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByNormalizedEmail, emailNormalized)
	var i GetUserByNormalizedEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PasswordVersion,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserForActionByNormalizedEmail = `-- name: GetUserForActionByNormalizedEmail :one
SELECT
    u.id,
    u.email,
    u.display_name,
    u.status,
    u.email_verified_at,
    EXISTS (
        SELECT 1
        FROM user_passwords AS p
        WHERE p.user_id = u.id
    ) AS has_password
FROM users AS u
WHERE u.email_normalized = $1
LIMIT 1
`

type GetUserForActionByNormalizedEmailRow struct {
	ID              pgtype.UUID
	Email           string
	DisplayName     string
	Status          UserStatus
	EmailVerifiedAt pgtype.Timestamptz
	HasPassword     bool
}

func (q *Queries) GetUserForActionByNormalizedEmail(ctx context.Context, emailNormalized string) (GetUserForActionByNormalizedEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserForActionByNormalizedEmail, emailNormalized)
	var i GetUserForActionByNormalizedEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.HasPassword,
	)
	return i, err
}

const getUserIdentityByNormalizedEmail = `-- name: GetUserIdentityByNormalizedEmail :one
SELECT id, email, email_normalized, display_name, status, email_verified_at,
       password_version, last_login_at, created_at, updated_at
FROM users
WHERE email_normalized = $1
`

func (q *Queries) GetUserIdentityByNormalizedEmail(ctx context.Context, emailNormalized string) (User, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByNormalizedEmail, emailNormalized)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PasswordVersion,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithPasswordForUpdate = `-- name: GetUserWithPasswordForUpdate :one
SELECT
    u.id,
    u.email,
    u.email_normalized,
    u.display_name,
    u.status,
    u.email_verified_at,
    u.password_version,
    p.password_hash,
    p.changed_at AS password_changed_at
FROM users AS u
JOIN user_passwords AS p ON p.user_id = u.id
WHERE u.id = $1
FOR UPDATE OF u, p
`

type GetUserWithPasswordForUpdateRow struct {
	ID                pgtype.UUID
	Email             string
	EmailNormalized   string
	DisplayName       string
	Status            UserStatus
	EmailVerifiedAt   pgtype.Timestamptz
	PasswordVersion   int64
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
}

func (q *Queries) GetUserWithPasswordForUpdate(ctx context.Context, userID pgtype.UUID) (GetUserWithPasswordForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserWithPasswordForUpdate, userID)
	var i GetUserWithPasswordForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PasswordVersion,
		&i.PasswordHash,
		&i.PasswordChangedAt,
	)
	return i, err
}

const incrementUserPasswordVersion = `-- name: IncrementUserPasswordVersion :one
UPDATE users
SET password_version = password_version + 1
WHERE id = $1
RETURNING
    id,
    password_version,
    updated_at
`

type IncrementUserPasswordVersionRow struct {
	ID              pgtype.UUID
	PasswordVersion int64
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) IncrementUserPasswordVersion(ctx context.Context, userID pgtype.UUID) (IncrementUserPasswordVersionRow, error) {
	row := q.db.QueryRow(ctx, incrementUserPasswordVersion, userID)
	var i IncrementUserPasswordVersionRow
	err := row.Scan(&i.ID, &i.PasswordVersion, &i.UpdatedAt)
	return i, err
}

const listUserActiveMemberships = `-- name: ListUserActiveMemberships :many
SELECT
    m.id AS membership_id,
    m.organization_id,
    m.status AS membership_status,
    m.authorization_version AS membership_authorization_version,
    m.default_store_id,
    m.joined_at,
    o.name AS organization_name,
    o.slug AS organization_slug,
    o.status AS organization_status,
    o.timezone AS organization_timezone,
    o.locale AS organization_locale,
    o.currency AS organization_currency,
    o.authorization_version AS organization_authorization_version,
    s.code AS default_store_code,
    s.name AS default_store_name,
    s.status AS default_store_status
FROM organization_memberships AS m
JOIN organizations AS o ON o.id = m.organization_id
LEFT JOIN stores AS s
  ON s.organization_id = m.organization_id
 AND s.id = m.default_store_id
WHERE m.user_id = $1
  AND m.status = 'ACTIVE'
  AND o.status = 'ACTIVE'
ORDER BY m.joined_at ASC, m.id ASC
`

type ListUserActiveMembershipsRow struct {
	MembershipID                     pgtype.UUID
	OrganizationID                   pgtype.UUID
	MembershipStatus                 MembershipStatus
	MembershipAuthorizationVersion   int64
	DefaultStoreID                   pgtype.UUID
	JoinedAt                         pgtype.Timestamptz
	OrganizationName                 string
	OrganizationSlug                 string
	OrganizationStatus               OrganizationStatus
	OrganizationTimezone             string
	OrganizationLocale               string
	OrganizationCurrency             string
	OrganizationAuthorizationVersion int64
	DefaultStoreCode                 pgtype.Text
	DefaultStoreName                 pgtype.Text
	DefaultStoreStatus               NullStoreStatus
}

func (q *Queries) ListUserActiveMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserActiveMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserActiveMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserActiveMembershipsRow{}
	for rows.Next() {
		var i ListUserActiveMembershipsRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.OrganizationID,
			&i.MembershipStatus,
			&i.MembershipAuthorizationVersion,
			&i.DefaultStoreID,
			&i.JoinedAt,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.OrganizationStatus,
			&i.OrganizationTimezone,
			&i.OrganizationLocale,
			&i.OrganizationCurrency,
			&i.OrganizationAuthorizationVersion,
			&i.DefaultStoreCode,
			&i.DefaultStoreName,
			&i.DefaultStoreStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :one
UPDATE users
SET display_name = $1
WHERE id = $2
RETURNING id, email, display_name, email_verified_at, updated_at
`

type UpdateUserDisplayNameParams struct {
	DisplayName string
	UserID      pgtype.UUID
}

type UpdateUserDisplayNameRow struct {
	ID              pgtype.UUID
	Email           string
	DisplayName     string
	EmailVerifiedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (UpdateUserDisplayNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserDisplayName, arg.DisplayName, arg.UserID)
	var i UpdateUserDisplayNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.EmailVerifiedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :one
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
RETURNING id, last_login_at, updated_at
`

type UpdateUserLastLoginRow struct {
	ID          pgtype.UUID
	LastLoginAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, userID pgtype.UUID) (UpdateUserLastLoginRow, error) {
	row := q.db.QueryRow(ctx, updateUserLastLogin, userID)
	var i UpdateUserLastLoginRow
	err := row.Scan(&i.ID, &i.LastLoginAt, &i.UpdatedAt)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE user_passwords
SET
    password_hash = $1,
    changed_at = NOW()
WHERE user_id = $2
RETURNING
    user_id,
    changed_at,
    created_at,
    updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UserID       pgtype.UUID
}

type UpdateUserPasswordRow struct {
	UserID    pgtype.UUID
	ChangedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.UserID)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.UserID,
		&i.ChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordAndIncrementVersion = `-- name: UpdateUserPasswordAndIncrementVersion :one
WITH updated_password AS (
    UPDATE user_passwords
    SET
        password_hash = $1,
        changed_at = NOW()
    WHERE user_id = $2
    RETURNING user_id, changed_at
), updated_user AS (
    UPDATE users AS u
    SET password_version = u.password_version + 1
    FROM updated_password AS p
    WHERE u.id = p.user_id
    RETURNING
        u.id,
        (u.password_version - 1)::BIGINT AS previous_password_version,
        u.password_version AS new_password_version
)
SELECT
    u.id,
    u.previous_password_version,
    u.new_password_version,
    p.changed_at
FROM updated_user AS u
JOIN updated_password AS p ON p.user_id = u.id
`

type UpdateUserPasswordAndIncrementVersionParams struct {
	PasswordHash string
	UserID       pgtype.UUID
}

type UpdateUserPasswordAndIncrementVersionRow struct {
	ID                      pgtype.UUID
	PreviousPasswordVersion int64
	NewPasswordVersion      int64
	ChangedAt               pgtype.Timestamptz
}

func (q *Queries) UpdateUserPasswordAndIncrementVersion(ctx context.Context, arg UpdateUserPasswordAndIncrementVersionParams) (UpdateUserPasswordAndIncrementVersionRow, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordAndIncrementVersion, arg.PasswordHash, arg.UserID)
	var i UpdateUserPasswordAndIncrementVersionRow
	err := row.Scan(
		&i.ID,
		&i.PreviousPasswordVersion,
		&i.NewPasswordVersion,
		&i.ChangedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, NOW())
WHERE id = $1
RETURNING
    id,
    email_verified_at,
    updated_at
`

type VerifyUserEmailRow struct {
	ID              pgtype.UUID
	EmailVerifiedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) VerifyUserEmail(ctx context.Context, userID pgtype.UUID) (VerifyUserEmailRow, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, userID)
	var i VerifyUserEmailRow
	err := row.Scan(&i.ID, &i.EmailVerifiedAt, &i.UpdatedAt)
	return i, err
}
