// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
WITH created_user AS (
    INSERT INTO users (
        email,
        email_normalized,
        display_name
    )
    VALUES (
        $1,
        $2,
        $3
    )
    RETURNING
        id,
        email,
        email_normalized,
        display_name,
        status,
        email_verified_at,
        password_version,
        last_login_at,
        created_at,
        updated_at
), created_password AS (
    INSERT INTO user_passwords (
        user_id,
        password_hash
    )
    SELECT
        id,
        $4
    FROM created_user
    RETURNING user_id
)
SELECT
    u.id,
    u.email,
    u.email_normalized,
    u.display_name,
    u.status,
    u.email_verified_at,
    u.password_version,
    u.last_login_at,
    u.created_at,
    u.updated_at
FROM created_user AS u
JOIN created_password AS p ON p.user_id = u.id
`

type CreateUserWithPasswordParams struct {
	Email           string
	EmailNormalized string
	DisplayName     string
	PasswordHash    string
}

type CreateUserWithPasswordRow struct {
	ID              pgtype.UUID
	Email           string
	EmailNormalized string
	DisplayName     string
	Status          UserStatus
	EmailVerifiedAt pgtype.Timestamptz
	PasswordVersion int64
	LastLoginAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword,
		arg.Email,
		arg.EmailNormalized,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i CreateUserWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PasswordVersion,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByNormalizedEmail = `-- name: GetUserByNormalizedEmail :one
SELECT
    u.id,
    u.email,
    u.email_normalized,
    u.display_name,
    u.status,
    u.email_verified_at,
    u.password_version,
    u.last_login_at,
    u.created_at,
    u.updated_at,
    p.password_hash,
    p.changed_at AS password_changed_at
FROM users AS u
JOIN user_passwords AS p ON p.user_id = u.id
WHERE u.email_normalized = $1
LIMIT 1
`

type GetUserByNormalizedEmailRow struct {
	ID                pgtype.UUID
	Email             string
	EmailNormalized   string
	DisplayName       string
	Status            UserStatus
	EmailVerifiedAt   pgtype.Timestamptz
	PasswordVersion   int64
	LastLoginAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	PasswordHash      string
	PasswordChangedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByNormalizedEmail(ctx context.Context, emailNormalized string) (GetUserByNormalizedEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByNormalizedEmail, emailNormalized)
	var i GetUserByNormalizedEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PasswordVersion,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.PasswordChangedAt,
	)
	return i, err
}

const incrementUserPasswordVersion = `-- name: IncrementUserPasswordVersion :one
UPDATE users
SET password_version = password_version + 1
WHERE id = $1
RETURNING
    id,
    password_version,
    updated_at
`

type IncrementUserPasswordVersionRow struct {
	ID              pgtype.UUID
	PasswordVersion int64
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) IncrementUserPasswordVersion(ctx context.Context, userID pgtype.UUID) (IncrementUserPasswordVersionRow, error) {
	row := q.db.QueryRow(ctx, incrementUserPasswordVersion, userID)
	var i IncrementUserPasswordVersionRow
	err := row.Scan(&i.ID, &i.PasswordVersion, &i.UpdatedAt)
	return i, err
}

const listUserActiveMemberships = `-- name: ListUserActiveMemberships :many
SELECT
    m.id AS membership_id,
    m.organization_id,
    m.authorization_version AS membership_authorization_version,
    m.default_store_id,
    m.joined_at,
    o.name AS organization_name,
    o.slug AS organization_slug,
    o.timezone AS organization_timezone,
    o.locale AS organization_locale,
    o.currency AS organization_currency,
    o.authorization_version AS organization_authorization_version,
    s.code AS default_store_code,
    s.name AS default_store_name,
    s.status AS default_store_status
FROM organization_memberships AS m
JOIN organizations AS o ON o.id = m.organization_id
LEFT JOIN stores AS s
  ON s.organization_id = m.organization_id
 AND s.id = m.default_store_id
WHERE m.user_id = $1
  AND m.status = 'ACTIVE'
  AND o.status = 'ACTIVE'
ORDER BY o.name ASC, o.id ASC, m.id ASC
`

type ListUserActiveMembershipsRow struct {
	MembershipID                     pgtype.UUID
	OrganizationID                   pgtype.UUID
	MembershipAuthorizationVersion   int64
	DefaultStoreID                   pgtype.UUID
	JoinedAt                         pgtype.Timestamptz
	OrganizationName                 string
	OrganizationSlug                 string
	OrganizationTimezone             string
	OrganizationLocale               string
	OrganizationCurrency             string
	OrganizationAuthorizationVersion int64
	DefaultStoreCode                 pgtype.Text
	DefaultStoreName                 pgtype.Text
	DefaultStoreStatus               NullStoreStatus
}

func (q *Queries) ListUserActiveMemberships(ctx context.Context, userID pgtype.UUID) ([]ListUserActiveMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserActiveMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserActiveMembershipsRow{}
	for rows.Next() {
		var i ListUserActiveMembershipsRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.OrganizationID,
			&i.MembershipAuthorizationVersion,
			&i.DefaultStoreID,
			&i.JoinedAt,
			&i.OrganizationName,
			&i.OrganizationSlug,
			&i.OrganizationTimezone,
			&i.OrganizationLocale,
			&i.OrganizationCurrency,
			&i.OrganizationAuthorizationVersion,
			&i.DefaultStoreCode,
			&i.DefaultStoreName,
			&i.DefaultStoreStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE user_passwords
SET
    password_hash = $1,
    changed_at = NOW()
WHERE user_id = $2
RETURNING
    user_id,
    changed_at,
    created_at,
    updated_at
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	UserID       pgtype.UUID
}

type UpdateUserPasswordRow struct {
	UserID    pgtype.UUID
	ChangedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (UpdateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.PasswordHash, arg.UserID)
	var i UpdateUserPasswordRow
	err := row.Scan(
		&i.UserID,
		&i.ChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users
SET email_verified_at = COALESCE(email_verified_at, NOW())
WHERE id = $1
RETURNING
    id,
    email_verified_at,
    updated_at
`

type VerifyUserEmailRow struct {
	ID              pgtype.UUID
	EmailVerifiedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) VerifyUserEmail(ctx context.Context, userID pgtype.UUID) (VerifyUserEmailRow, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, userID)
	var i VerifyUserEmailRow
	err := row.Scan(&i.ID, &i.EmailVerifiedAt, &i.UpdatedAt)
	return i, err
}
